google/ksp

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSFunctionDeclaration.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/CheckOverrideProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSFunctionDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSPropertyDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt
compiler-plugin/testData/api/checkOverride.kt

Although Java does not have property concept, Kotlin compiler still generate for them for certain functions obeying naming convention.

Refactor override checking API, fix override checking for property accessors from Java.

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyAccessor.kt

related issue: #97 
Actually, I am not sure if this is the right way to document it. Use-site target is more than just accessors, and only documenting accessors seems not full coverage. But some use-site targets doesn't really have a place in Kotlin, such as `@field` .
We do already have documentation on `KSAnnotated.findAnnotationFromUseSiteTarget()` in utils, but I admit it is not very straightforward to find when it comes to its desired use case.
cc @yigit

Enhance document on KSPropertyAccessor on how to get full annotations for an accessor

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ErrorTypeProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceJavaImpl.kt
compiler-plugin/testData/api/allFunctions.kt
compiler-plugin/testData/api/errorTypes.kt

KotlinType is making such error type into a flexible type, need to
check if the declaration of the bounds of this flexible type is an
instance of NotFoundClasses.MockClassDescriptor.
It might be a temporary workaround as it appears to be `resolveJavaType()` not handling all error types, could have something to do with the `JavaType` construction before delegating to compiler API.

Handle unresolved types for types from Java symbols.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/CheckOverrideProcessor.kt
compiler-plugin/testData/api/checkOverride.kt

This PR fixes a bug where override would return `true` if base method is sent as the overrider.
Similarly, it was also returning true when override is called with the same function itself.
I've also changed the override util call to also check for return type.
Fixes: #123

Check for type hierarchy while checking overrides

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
gradle-plugin/build.gradle.kts
gradle-plugin/src/main/java/com/google/devtools/ksp/gradle/InternalTrampoline.java
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Also turn incremental compilation back on.
Note that incremental processing is still under construction.

Move KSP to an independent Gradle task

---

gradle-plugin/src/main/java/com/google/devtools/ksp/gradle/InternalTrampoline.java
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Set destinationDir for KotlinCompileTaskData.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationsInDependenciesProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/annotationInDependencies.kt

This commit fixes an issue where KSP would drop annotations
on properties if the property is read from a compiled code and
the annotation has field target. I fixed it by also reading
annotations on the backing field for compiled classes.
Unfortunately, the way KSP reports a kotlin class coming from
source vs compiled code is still not the same. In compiled code,
annotations that target getter/setters are reported via the generated
synthetic in .class files vs they are reported on the property in
source files.
So added tests with data class and changed the test to
ignore the difference between getting a targeted annotation
on a property vs on its getter/setter.
We might want to change it going forward but either case it would probably
be difficult to distinguish. This is luckily is not the …

fix property backing field annotations

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArrayValueProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/annotationValue.kt
compiler-plugin/testData/api/annotationWithArrayValue.kt
compiler-plugin/testData/api/annotationWithDefault.kt

This commit fixes multiple issues in annotation parsing for java code
1) When getting annotation names, it was always using the index instead
of the name. I changed it to default to name and only use index if
name is not provided.
2) Array values in annotations were repoted as a list of pairs instead
of 1 key and multiple values, fixed.
3) When the annotation value is a type, it was not returning a KSType
but instead returning a PsiType, fixed.
4) When the annotation value is another annotation, it was not returning
a KSAnnotation, fixed.
5) For expressions resolving to literals, it was returning the PsiLiteral
instead of the value of it.
6) TypeReferences (relevant in enum values) were not being resolved.
Updated/added tests for all cases above.
The enum fix for java source is not great …

Fix various java annotation parsing issues

---

api/src/main/kotlin/com/google/devtools/ksp/KspExperimental.kt
api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/MangledNamesProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/MapSignatureProcessor.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
compiler-plugin/testData/api/mangledNames.kt

This PR adds a new API `getJvmName` to get the jvm name of a method or accessor.
This is crucial for annotation processors that generate java source code as they might need to access internal methods in the same module compilation (as it works w/ KAPT).
Fixes #129

Add APIs to get JVM names of functions and property accessors

---

.github/workflows/main.yml

set:env is disabled due to a security warning.
We don't have anything sensitive in this build so it is fine
for us to keep using it for now.

allow setting env variables in workflow

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSFunctionDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/OverrideeProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSFunctionDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/overridee.kt

This CL fixes a few problems in find overridee implementation:
a) If the method does not override anything, it would throw instead of
returning null, fixed.
b) If it overrides a method that overrides another method, it would
return null, now it returns the first actual override.
c) If it overrides a method from a GrandSuper (where super does not
override it), it would return null. Now it returns the method in
GrandSuper class.
Fixes: #150

Fix find overridee, add tests

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
api/src/main/kotlin/com/google/devtools/ksp/visitor/KSValidateVisitor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ValidateProcessor.kt
compiler-plugin/testData/api/validateTypes.kt

Annotation argument values are left out for check for now.

add annotation validation to validate API

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/OverrideeProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/overridee.kt

This CL updates KSPropertyDecl.findOverridee to use the same infra
that is used by KSFunctionDeclaration.
Fixes: #174

FIx findOverridee for properties, fixes #174

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeAliasDescriptorImpl.kt
compiler-plugin/testData/api/annotationValue.kt

There is implicit type aliasing happening for certain Kotlin standard library classes, if not imported explicitly for its true type, will be presented as a type alias through resolution.

add KSTypeAliasDescriptorImpl

---

api/src/main/kotlin/com/google/devtools/ksp/processing/CodeGenerator.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/CodeGeneratorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
gradle-plugin/src/main/java/com/google/devtools/ksp/gradle/KspTaskJ.java
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

For now, changes in other modules, external libraries and Java sources will trigger a full rebuild.
It is disabled by default and can be switched on by the Gradle property `ksp.incremental=true`.

Incremental processing for Kotlin sources

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/MapSignatureProcessor.kt
compiler-plugin/testData/api/signatureMapper.kt

This PR fixes a bug where KSP failed to resolve the java
declaration for a java method if its name starts with get
or set.
Fixes: #200
Test: signatureMapper

Fix resolveJavaDeclaration for get/set methods

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

So that it can be picked up by compilation and jar tasks.

Add generated resource dir to proper sources and outputs

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AllFunctionsProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/allFunctions.kt

When a java class implements a kotlin interface that declared a property,
the descriptor could resolve to a PsiMethod for which we don't have a
property implementation (because there is another matching method so single
method is not enough). For those cases, fall back to the descriptor implementation.
Test: allFunctions.kt
Fixes: #216

Use property descriptor impl for java properties

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt

1. mkdir() before writing logs. In some cases, `build` isn't created by
Gradle.
2. Add a timestamp for each build.

Refine incremental logs

---

api/build.gradle.kts
build.gradle.kts
gradle-plugin/build.gradle.kts
gradle-plugin/src/main/resources/META-INF/gradle-plugins/symbol-processing.properties
gradle/wrapper/gradle-wrapper.properties
symbol-processing/build.gradle.kts

This CL updates the build to properly publish the gradle
plugin with an id to avoid the need to modify settings
gradle.
After this change, we'll have the following 4 artifacts:
symbol-processing-api: same as before
symbol-processing: does not include the the gradle-plugin anymore
symbol-processing-gradle-plugin: the gradle plugin
com.google.devtools.ksp.gradle.plugin: gradle plugin marker artifact
After this change, developer can enable KSP by:
id("com.google.devtools.ksp")
* Still needs to have google as a plugin repository.
The gradle plugin publishing model requires publishing a marker artifact
so that Gradle can find the main plugin artifact.
I've added `java-gradle-plugin` plugin to the gradle-plugin module to
enable publishing. Unfortunately, it does have a validation step which …

Gradle plugin publishing setup

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/JavaModifierProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
compiler-plugin/testData/api/javaModifiers.kt

This PR fixes a bug where the inner modifier would be lost if the
kotlin sources is in dependencies (when wrapped in a descriptor).
Unfortunately, for descriptors, there is no easy way to distinguish
between JAVA_STATIC and INNER. That is, if a java nested class that is
annotated with STATIC is compiled, descriptor API will no longer report
any modifiers for it. Similarly, if a Java inner class (that has no
static annotation) is compiled, we'll start reporting INNER for it.
Even though this is slightly confusing, it is at least consistent from a
kotlin perspective.
Also fixed a bug in multi-module testing setup where we were NOT
compiling java sources in test modules.
Fixes: #231
Test: javaModifiers
more test cases
report inner for descriptors

Report INNER modifier for class descriptors

---

compiler-plugin/build.gradle.kts
symbol-processing/build.gradle.kts

To be able to do composite build, KSP depends on kotlin-compiler rather
than kotlin-compiler-embeddable and uses ShadowJar to relocate some
symbols. Unfortunately, ShadowJar doesn't seem able to relocate the jar
only and generate proper dependencies in the POM. As a workaround, this
commit hard-coded the dependencies.

Setup depenedencies in compiler plugin's POM

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt

Not sure why but the following error seems to appear on Linux only. This commit makes the error gone, but I'm not sure whether it is the right solution. Still investigating...
```
directory not found: /tmp/tmp170292837443557314.tmp/testRootGW4/unitTest_multipleModules/test/module1/javaOut
java.lang.IllegalStateException: directory not found: /tmp/tmp170292837443557314.tmp/testRootGW4/unitTest_multipleModules/test/module1/javaOut
at com.sun.tools.javac.main.Main.error(Main.java:186)
at com.sun.tools.javac.main.Main.checkDirectory(Main.java:345)
at com.sun.tools.javac.main.Main.processArgs(Main.java:274)
at com.sun.tools.javac.main.Main.compile(Main.java:414)
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
at …
```

multi-module tests: make sure javaOut exists before passing to compiler

---

README.md

Also reflects that plugin-id has been changed from `symbol-processing`
to `com.google.devtools.ksp` and overriding `resolutionStrategy` is no
longer needed.

update README.md to ksp-1.4.20-dev-experimental-20210107

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaEnumEntryImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/testData/api/classKinds.kt

So that it is more consistent from Kotlin's point of view.

Model Java enum entries as KSClassDeclaration

---

compiler-plugin/build.gradle.kts

Mute an "idea home not valid" error in tests

---

symbol-processing/build.gradle.kts

ShadowJar picks up the `compile` configuration by default and pulls
stdlib in (when using `from` without changing `configurations`).

Fine tuning contents of symbol-processing.jar

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

JavaCompile task will process only *.java files,
and resources need to registered using different
mechanism.
This fixes https://github.com/google/ksp/issues/244.

Do not register resources as Java sources

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Seems like KMP project with targets other than JVM cause NullPointerException after connecting symbol processing plugin. 
After that fix (and local publish) I was able to use JVM KSP in multiplatform project

Fix NullPointerException on adding plugin to KMP project

---

api/src/main/kotlin/com/google/devtools/ksp/processing/KSPLogger.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/MessageCollectorBasedKSPLogger.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ErrorTypeProcessor.kt

~~When seeing errors or exceptions in logger event, pass the original binding context back to fail compilation.~~
~~This is quite tricky since there might be errors recorded in processor that are not related to compiler errors. A better solution need to change compiler plugin extension point to support such custom 'fail on sight' style `AnalysisResult`. Alternatively it is also doable to just throw exception in KSP to fail compilation but that might be too aggressive.~~
Since error out works now, we no longer need to fail compilation here, however it is still worth to expose logger statistics for future usage.

Expose logger statistics

---

.github/workflows/main.yml

Unfortunately I forgot to change the name of upload when copying the entries from test and the report of test was overwritten.

Rename reports of integration tests

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/MapSignatureProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ResolveJavaTypeProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/resolveJavaType.kt
compiler-plugin/testData/api/signatureMapper.kt

This PR fixes a bug where we were wrapping all PsiMethods to
JavaMethodImpl without checking if they are constructors.
Both cases, we were wrapping them to find the containing class,
so I've added an extension function to ModuleClassResolver
to find containing descriptor via PsiMethod which abstracts
this resolution.
Test: extended resolveJavaType and signatureMapper tests to trigger
the crash
Fixes: #265

Properly wrap PSIMethods that are constructors

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Will add a test after #269 is merged.

Copy compiler args from compileKotlin to kspKotlin

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/CheckOverrideProcessor.kt
compiler-plugin/testData/api/checkOverride.kt

Current override checking utilize `OverridingUtil` which appears to be unable to handle concrete types when overriding a member from a generic super type. After peeking into the structure of `CallableMemberDecriptor` for a while, a BFS looks promising.

change override checking logic to traverse CallableMemberDescriptor.overriddenDescriptors()

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AllFunctionsProcessor.kt
compiler-plugin/testData/api/allFunctions.kt

This is a no-op test refactor. allFunctions test was sorting all
declarations globally, making it hard to read what has changed when
a new declaration shows up.
This PR updates it to only sort in class level per group (functions,
declarations) so that the output is more clear to read and validate
visually.

Refactor all functions test to report by class

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt

There are some resolutions that don't lookup binding context and rewrote
the slice. Therefore, the annotation resolution is rewritten to use the
same call path as those in-compiler accesses to avoid the conflict.

Workaround for some unchecked accesses

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationsInDependenciesProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/DeclarationUtilProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/testData/api/annotationInDependencies.kt
compiler-plugin/testData/api/constructorDeclarations.kt
compiler-plugin/testData/api/declarationUtil.kt
compiler-plugin/testData/api/implicitElements.kt

PR #275 made different class declaration backends more consistent
by adding constructor into declarations and making getConstructors
return based on that.
Unfortunately, it missed primary constructor, causing missing
constructors OR even worse, return an empty constructor
instead of the primary constructor.
This PR fixes that issue and also extends the test case to
cover it.
Fixes: #279

return primary constructor in declarations for KSClassDeclarationImpl

---

.github/workflows/release.yml

It sets `kspVersion` by the tag name associated in a release.
There are 2 differences to main.yml:
1. events
2. actions after # Build KSP artifacts

Build & upload artifact on release

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/VersionCheckIT.kt
integration-tests/src/test/resources/playground/build.gradle.kts

Each KSP release depends on a specific Kotlin compiler version.
If their versions don't match, there might be runtime errors.

Check KSP and kotlin-gradle-plugin versions

---

.github/workflows/main.yml
build.gradle.kts
gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt

This PR adds code to register generated java sources with AGP so that
the IDE can discover them (useful when developer needs to debug
generated code or their code needs to access them).
I had to update AGP dependency to the plugin (instead of the API)
because the plugin does not yet provide the api to register generated
resource folders.
For some reason, the generated byte code sources gets overridden by the
kotlin path, hence, I couldn't assert them in tests.
Test: SourceSetConfigurationTest.registerJavaSourcesToAndroid

Register generated java sources with AGP

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OnErrorIT.kt
integration-tests/src/test/resources/on-error/build.gradle.kts
integration-tests/src/test/resources/on-error/on-error-processor/build.gradle.kts
integration-tests/src/test/resources/on-error/on-error-processor/src/main/kotlin/ErrorProcessor.kt
integration-tests/src/test/resources/on-error/on-error-processor/src/main/kotlin/NormalProcessor.kt
integration-tests/src/test/resources/on-error/on-error-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessor
integration-tests/src/test/resources/on-error/settings.gradle.kts
integration-tests/src/test/resources/on-error/workload/build.gradle.kts
integration-tests/src/test/resources/on-error/workload/src/main/java/com/example/A.kt

I tried to test the `onError` behavior with logger.warn but it seems warnings are shadowed in case of errors.. Probably need another fix to make it work properly.

add integration test for onError

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationOnConstructorParameterProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/annotationOnConstructorParameter.kt

This also works around a compiler behavior that annotations on
constructor parameters are omitted in the corresponding
PropertyDescriptor.
Fixes #310

Use psi for getAllFunctions / getAllProperties if possible

---

api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AbstractTestProcessor.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/processor/TestSymbolProcessor.kt
integration-tests/src/test/resources/incremental/validator/src/main/kotlin/Validator.kt
integration-tests/src/test/resources/on-error/on-error-processor/src/main/kotlin/ErrorProcessor.kt
integration-tests/src/test/resources/on-error/on-error-processor/src/main/kotlin/NormalProcessor.kt
integration-tests/src/test/resources/output-deps/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/BuilderProcessor.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt

Per chat in the kotlin-lang channel, this function often doesn't need implementing in processors and saves users a bit of boilerplate.

Make finish() have a default implementation

---

docs/examples.md
docs/incremental.md
docs/multi-round.md

Fix missing syntax highlighting for Kotlin code in docs.

Add syntax highlighting to docs

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSClassDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaEnumEntryImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSErrorTypeClassDeclaration.kt

Resolves #218
Starting early for review. Next steps:
* Do we need to add in incremental tracking now or wait till Kotlin 1.5?
* Do we expose the same for Java 15 "permitted subtypes" if JVM target is set to 15+ and 1.5 language version is set?
* Tests!

Implement getSealedSubclasses API on KSClassDeclaration

---

integration-tests/build.gradle.kts
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt
integration-tests/src/test/resources/playground-android/build.gradle.kts
integration-tests/src/test/resources/playground-android/gradle.properties
integration-tests/src/test/resources/playground-android/settings.gradle.kts
integration-tests/src/test/resources/playground-android/test-processor/build.gradle.kts
integration-tests/src/test/resources/playground-android/test-processor/src/main/kotlin/Builder.kt
integration-tests/src/test/resources/playground-android/test-processor/src/main/kotlin/BuilderProcessor.kt
integration-tests/src/test/resources/playground-android/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/playground-android/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessor
integration-tests/src/test/resources/playground-android/workload/build.gradle.kts
integration-tests/src/test/resources/playground-android/workload/src/main/AndroidManifest.xml
integration-tests/src/test/resources/playground-android/workload/src/main/java/com/example/A.kt
integration-tests/src/test/resources/playground-android/workload/src/main/java/com/example/AClass.kt

In `workload/build.gradle.kts`, the order of plugins is critical. The test would fail with the following message without #318.
```
Extension of type 'CommonExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KspExtension]
```

More tests for AGP support

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OutputDepsIt.kt
integration-tests/src/test/resources/output-deps/test-processor/src/main/kotlin/TestProcessor.kt

Clean files should be calculated with the up-to-date sourceToOutputsMap.
Also add reprocessed sources and outputs in `kspSourceToOutputsMap.log`.
Fixes #327

Update sourceToOutputsMap before restoring outputs

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OutputDepsIt.kt

Sleep longer than some environment's timestamp precision (1 second).

Fix integration test for #329

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/MultiplatformIT.kt
integration-tests/src/test/resources/playground-mpp/build.gradle.kts
integration-tests/src/test/resources/playground-mpp/settings.gradle.kts
integration-tests/src/test/resources/playground-mpp/test-processor/build.gradle.kts
integration-tests/src/test/resources/playground-mpp/workload/build.gradle.kts

With MPP, `KotlinPluginWrapper` isn't always applied and the source set
`main` may not exist.

Always include the main `ksp` configuration

---

.editorconfig
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
buildSrc/src/main/kotlin/com/google/devtools/ksp/Ktlint.kt
settings.gradle.kts

It is a fork of what androidX does with minor modifications.
There are 3 new tasks:
rootProject:ktlintApplyToIdea -> Applied ktlint configuration to the
current .idea project folder
<subproject>:ktlint -> Runs ktlint checks
<subproject>:ktlintFormat -> Fixes formatting for the project. Note that
this may not be able to handle all violations.
I've not modified the CI files to run this since it fails right now. One
of the core maintaners should run the format tasks to come to a clean
slate then we can add it to CI. I've not added a baseline file since
they are very brittle.

Integrate ktlint

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/NestedClassTypeProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeArgumentDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeReferenceDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeArgumentJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/nestedClassType.kt
compiler-plugin/testData/api/resolveJavaType.kt

Basically just use descriptors to get type arguments from parent class(es).
Also found a bug in `KSTypeArgumentJavaImpl` for `<?>` where the original implementation does not align with compiler behavior. Although with this change, source based `KSTypeArgument` implementations looks to be obsolete as we use descriptors for everything now, probably better to remove all these implementations.

fix type arguments for inner classes

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/JavaModifierProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/javaModifiers.kt

This PR improves how we detect JAVA_STATIC modifier in declarations.
For descriptors, it wasn't showing up at all as the Descriptor API does
not have an API to return it. This change checks the containing
declaration's static scope to decide.
To be more consistent, I've also added checks for JvmStatic for both
descriptor and declaration implementation. I cached the ClassDeclaration
in Resolver (not great but does the job).
Also fixed another issue where we could add OPEN modifier based on
modality without checking if it is private or not. Added that logic into
the Descriptor -> Modifiers converter.
Fixes: #231
Test: javaModifiers

Improvements on JAVA_STATIC modifier detection

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/GetPackageProcessor.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/getPackage.kt

TODO: Isolate symbol look up from module descriptor for symbols from source if possible. Current implementation is resolving through descriptors even for symbols from source therefore can cause unnecessary overhead due to symbol resolution.

Add Resolver.getDeclarationsFromPackage() API for getting declarations with a given package name.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/GeneratedRefsIncIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/GeneratedSrcsIncIT.kt
integration-tests/src/test/resources/refs-gen/workload/src/main/kotlin/com/example/Baz.kt

Add generated files to symbolsMap in subsequent builds

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/TopLevelMemberProcessor.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/topLevelMembers.kt

This PR adds a new Resolver API to get the binary class name for the
owner of a function / property declaration.
(resolver.getOwnerJvmClassName)
For top level functions/properties; this value is necessary to be able
to generate Java code.
An alternative solution would be to synthesize KSClassDeclaration for
these top level members but that carries over JVM limitations to KSP
which is not great in the long term. This solution instead provides an
API to unblock Java code generating KSP Processors without taking much of
technical debt for KMP.
Fixes: #396
Test: topLevelMembers.kt

Add support for getting owner class binary name for members

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/GetSealedSubclassesIncIT.kt
integration-tests/src/test/resources/refs-gen/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/sealed-subclasses/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/sealed-subclasses/workload/src/main/kotlin/com/example/Impl1.kt
integration-tests/src/test/resources/sealed-subclasses/workload/src/main/kotlin/com/example/Impl2.kt
integration-tests/src/test/resources/sealed-subclasses/workload/src/main/kotlin/com/example/Sealed.kt
integration-tests/src/test/resources/srcs-gen/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/test-processor/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessor
integration-tests/src/test/resources/test-processor/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider

`sealedMap` is introduced to track sealed interfaces and classes. It is a map from file to FQNs.
Unfortunately, There isn't a simple way to associate symbols with their supertypes without resolution, because of typealias. Therefore, all sealed classes / interfaces on which getSealedSubclasses is called are invalidated.
Fixes #323

Incremental processing: support getSealedSubclasses from multiple files

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSType.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/FunctionTypeProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSErrorType.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/functionTypes.kt

It would be cumbersome to implement in user space by looking up the
fully qualified names. Let's provide it in the API since compiler
already knows it.
fixes #118

Introduce KSType.isFunctionType and KSType.isSuspendFunctionType

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSFunctionDeclaration.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AsMemberOfProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaAsMemberOfProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSFunctionDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSPropertyDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt

They are more convenient and object oriented.
fixes #208

Introduce asMemberOf to KSPropertyDeclaration and KSFunctionDeclaration

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
api/src/main/kotlin/com/google/devtools/ksp/utils.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/JavaToKotlinMapProcessor.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/javaToKotlinMapper.kt

They map Java classes to Kotlin classes and vice versa. For example,
java.lang.String <-> kotlin.String
java.lang.Integer <-> kotlin.Int
See https://kotlinlang.org/docs/java-interop.html#mapped-types for
details.
Also introduced two extension functions that loads Java/Kotlin as Kotlin/Java classes when applicable.
Fixes #126

Introduce mapJavaToKotlin and mapKotlinToJava to Resolver

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/Origin.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/LibOriginsProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ReferenceElementProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassifierReferenceDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSFunctionDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyAccessorDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyGetterDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeAliasDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeArgumentDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeParameterDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeReferenceDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSValueParameterDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyGetterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSPropertyGetterSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSTypeReferenceSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSValueParameterSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/crossModuleTypeAlias.kt
compiler-plugin/testData/api/getPackage.kt
compiler-plugin/testData/api/libOrigins.kt
compiler-plugin/testData/api/multipleModules.kt

For KSAnnotationDescriptor, check whether the underlying descripter is
JavaAnnotationDescriptor.
For KSDeclarationDescriptorImpl, KSPropertyAccessorDescriptorImpl and
KSValueParameterDescriptorImpl, check whether they are contained by
JavaClassDescriptor.
For KSTypeReferenceDescriptorImpl, KSClassifierReferenceDescriptorImpl
and KSTypeArgumentDescriptorImpl, specify the origin in their creation
appropriately. Most of time it is the same as where they are created.
The only exception is when it's created for type arguemnts from KotlinType.
In that case it is SYNTHETIC.

Split Origin.CLASS into KOTLIN_LIB and JAVA_LIB

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/DocStringProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaEnumEntryImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSPropertyDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeParameterJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSErrorTypeClassDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/docString.kt

A doc string is a string in the comment right in front of an declaration
and is enclosed by /** and */. Leading whitespaces and * are removed for
each line.

Support KSDeclaration.getDocString

---

api/build.gradle.kts
compiler-plugin/build.gradle.kts
gradle-plugin/build.gradle.kts

Kotlin 1.5 now targets JVM 1.8 [by defaut](https://kotlinlang.org/docs/whatsnew15.html#new-default-jvm-target-1-8), so there's no need to specify it again explicitly.

Remove kotlinOptions.jvmTarget specification

---

README.md
api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessorEnvironemnt.kt
api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessorProvider.kt
api/src/main/kotlin/com/google/devtools/ksp/visitor/KSValidateVisitor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/LegacySymbolProcessorAdapter.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/AbstractTestProcessor.kt
docs/quickstart.md
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/processor/TestSymbolProcessorProvider.kt
integration-tests/src/test/resources/init-plus-provider/provider-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/output-deps/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/refs-gen/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/sealed-subclasses/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/srcs-gen/test-processor/src/main/kotlin/TestProcessor.kt

This allows future arguments to be added without forcing changes to downstream
processors. Naming is modeled after apt's ProcessingEnvironment.

Extract create args to SymbolProcessorEnvironment

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt

Right now, `apOptions` are internal to the KSP Gradle plugin. Reading these options is useful for other Gradle plugins that might want to interact with KSP and options passed to it. For example the [prefiller plugin](https://github.com/simonschiller/prefiller) I'm maintaining needs access to some arguments passed to Room.
Both [KAPT](https://github.com/JetBrains/kotlin/blob/617d99faac5ba0b9cb5dc1957b10b01153b94c4f/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KaptExtension.kt#L104-L108) and [Java APT](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/gradle-core/src/main/java/com/android/build/gradle/api/AnnotationProcessorOptions.java;l=36-42;drc=b9f365bba6605d0adf19f88a311e808906f31e1c) also …

Make KSP arguments public

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/testData/api/getPackage.kt

Previous implementation is using module descriptor which is specified as `Kotlin module` therefore not including Java symbols.

fix an issue where getDeclarationsFromPackage not including java symbols

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/GetPackageProcessor.kt
compiler-plugin/testData/api/getPackage.kt

A follow up on #442 
Actually module descriptor is able to find symbols from Java source iff the said class is sitting in the file with name and path following Java convention, i.e. for a class `main.C`, it has to be in a file of path `/main/C.java`, therefore ignoring other classes in the same file, or any files not following path convention. With that, a distinct call is needed to filter redundant classes found.

fix getDeclarationsFromPackage to exclude symbols found in module descriptor

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/BackingFieldProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSPropertyDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/backingFields.kt

Unfortunately, the compiler API does not cover deserialized descriptors fully so I've implemented a custom binary class visitor to check that (provided by  @ting-yuan )

Add API to check if a property has a backing field

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Previously, kotlin-gradle-plugin names compiler plugin configuration
after PLUGIN_CLASSPATH_CONFIGURATION_NAME, now it is postfixed by target
and source set names.

Update implementation of blockOtherCompilerPlugins

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/AsMemberOfProcessor.kt
compiler-plugin/testData/api/asMemberOf.kt

fixes #462 
Current fix relies on the underlying naming convention for `JavaPropertyAccessor` from Kotlin compiler, which might change and break logic. Ultimate change should happen in upstream to fill out the `TODO` for `PropertyAccessorDescriptorImpl`

add a workaround for unsupported type substitution for property accessors

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

KotlinCompile isn't serializable and not compatible with Gradle
configuration cache.
Fixes #448

Remove reference to KotlinCompile in KspTask

---

integration-tests/src/test/resources/playground-android/gradle.properties

So as to fix recent OOMEs in `:workload:lint` in `AndroidIT` in CI:
https://github.com/google/ksp/actions/runs/941534021
https://github.com/google/ksp/actions/runs/949022386
https://github.com/google/ksp/actions/runs/962579576

Adjust heap size for AndroidIT

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/resources/kmp/build.gradle.kts
integration-tests/src/test/resources/kmp/settings.gradle.kts
integration-tests/src/test/resources/kmp/test-processor/build.gradle.kts
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/src/main/kotlin/com/example/Bar.kt
integration-tests/src/test/resources/kmp/workload/src/main/kotlin/com/example/Baz.kt

Currently, only a single `ksp()` configuration is supported in KMP, because the targets are added in configuration. Configurations like `kspJsMain` doesn't seem to be possible unless we built them unconditionally from presets. Unsupported targets are skipped by the else case in `val kspTaskClass = when (kotlinCompileTask) { ... }` around KspSubplugin.kt:246.
Also changed the path of KSP's output so as to accommodate different targets.

Support K/JS and K/Metadata

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt

Some third party projects invokes KSP in a different way.
Changes in KotlinSymbolProcessingPlugin may break them accidentally.
Do our best to notify them.

Add a reminder on the implication of certain changes

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

instead of AbstractKotlinCompile.Configurator.configure, which misses JS
specific configurations.

KspTaskJS: call inherited Configurator.configure

---

build.gradle.kts
compiler-plugin/build.gradle.kts
settings.gradle.kts

This PR updates the repositories list to be able to resolve snapshot versions of Kotlin and Idea dependencies.
I recently cloned this repo to address an issue and noted that Kotlin's Bintray repository was down and the JetBrains's Snapshots one missing.

Fixed Maven repositories

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

The KspTask.apOptions is solely used to let Gradle invalidate the build
whenever there is a change in options to processors. Previously it was
implmented by a default function. This commit reimplements it in a more
Gradle idiomatic way to avoid some potential issues with Gradle.

Register options to processors when registering KSP tasks

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/DualLookupTracker.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
docs/incremental.md
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalCPIT.kt
integration-tests/src/test/resources/incremental-classpath/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/gradle.properties
integration-tests/src/test/resources/incremental-classpath/l1/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/l1/src/main/kotlin/p1/L1.kt
integration-tests/src/test/resources/incremental-classpath/l2/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/l2/src/main/kotlin/p1/L2.kt
integration-tests/src/test/resources/incremental-classpath/l3/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/l3/src/main/kotlin/p1/L3.kt
integration-tests/src/test/resources/incremental-classpath/settings.gradle.kts
integration-tests/src/test/resources/incremental-classpath/validator/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/validator/src/main/kotlin/Validator.kt
integration-tests/src/test/resources/incremental-classpath/validator/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/incremental-classpath/workload/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/workload/src/main/kotlin/p1/K1.kt
integration-tests/src/test/resources/incremental-classpath/workload/src/main/kotlin/p1/K2.kt
integration-tests/src/test/resources/incremental-classpath/workload/src/main/kotlin/p1/K3.kt

This PR uses KAPT's `KaptTask.findClasspathChanges` to find classpath changes and invalidate source files accordingly.
Note that lookups are tracked at symbol level (e.g., class names, function names, etc) in the compiler. Also, `KaptTask.findClasspathChanges` finds changed classes rather than symbols. Therefore `DualLookupTracker` is introduced to emulate source-to-declarations-of-a-class lookups.

Incremental: support finer-grained classpath changes

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

The former is deprecated and will be removed in Gradle 8.0.

Gradle: replace destinationDir with destinationDirectory

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/JavaOnlyIT.kt
integration-tests/src/test/resources/java-only/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/java-only/workload/src/main/java/com/example/Foo.java

If there's no Java either, Gradle will skip the task. (NO-SOURCE)

JVM: run processors even without Kotlin sources

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/src/main/kotlin/Main.kt
symbol-processing/build.gradle.kts

Also publish `symbol-processing-cmdline` to be used with `kotlin-compiler` for command line and K/N.

Support Kotlin Native

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/KSPCompilationError.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Instead of throwing an NPE, report compilation error with proper error message.

Handle illegal function declarations

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

This change avoid computing SubpluginOption(s) eagerly, and it uses
ListProperty to capture them in a lazy way. This also ensures
that configure on demand works if ksp processor is defined in
a local project.
Fixes #518
Test: PlaygroundIT.testBuildWithConfigureOnDemand

Do not resolve configuration during configuration phase

---

build.gradle.kts

so that it doesn't depend on the JDK used to build KSP.
Kotlin compiler defaults to Java 8.

Set Java compatibility to Java 8

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt

...for most of the tests. It is still disabled in 2 test:
1. AndroidIT's assembleRelease is still failing and under investigation.
2. K/N compilation doesn't support configuration cache yet.
Real change is in ea681b3, which avoids referencing project in execution phase.
Also upgraded AGP to 7.0.0.

Enable configuration cache in integration tests

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeReferenceImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/NullableTypeProcessor.kt
compiler-plugin/testData/api/nullableTypes.kt

Get annotations and modifiers recursively from inner types. Note that
annotations and modifiers can only exist in one of the inner types.
Fixes #354

Annotations / modifiers for nullable / parenthesized types

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/GetSymbolsFromAnnotationProcessor.kt
compiler-plugin/testData/api/getSymbolsFromAnnotation.kt

so that aliasing names can be used in
1. argument to getSymbolsWithAnnotation, and
2. annotations on program elements.
For example, for input source
typealias Alias = Anno
@Alias
class C
A processor can obtain the KSAnnotated for C via
Resolver.getSymbolsWithAnnotation("Alias")
as well as
Resolver.getSymbolsWithAnnotation("Anno")

Support typealias in getSymbolsWithAnnotation

---

build.gradle.kts

Gradle Nexus Publish Plugin relies on it to determine correct
destination repository, i.e., release staging or snapshot.

Set version in root build.gradle.kts

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ResolveJavaTypeProcessor.kt
compiler-plugin/testData/api/resolveJavaType.kt

Skip synthetic Java methods when constructing resolution scope

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/AnnotatedUtilProcessor.kt
compiler-plugin/testData/api/annotatedUtil.kt
compiler-plugin/testData/api/javaAnnotatedUtil.kt

- mirror get annotation methods from Java
- Added support for the following extension functions 
- KSAnnotated#isAnnotationPresent
- KSAnnotated#getAnnotationsByType

Add support for KSAnnotated annotation methods 

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/LibOriginsProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/PlatformDeclarationProcessor.kt
compiler-plugin/testData/api/parent.kt
integration-tests/src/test/resources/output-deps/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/BuilderProcessor.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt

also fixed `parent` implementation where `KSFile` is not considered as a valid parent.

change KSDeclaration.containingFile to an extension property on KSNode

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/DeclarationOrderProcessor.kt
compiler-plugin/testData/api/declarationOrder.kt

which is same as KSDeclarationContainer.declarations, except that the
order of retrived declarations match their positions in source.
This is adapted from https://github.com/google/ksp/pull/260, which is
authored by Yigit Boyar <yboyar@google.com>.

Add experimental KSDeclarationContainer.declarationsInSourceOrder

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/playground/workload/G.kt
integration-tests/src/test/resources/playground/workload/build.gradle.kts

instead of default source set and its dependencies.
There are 3 ways (that I know of) to register extra sources to
compilation tasks:
1. Add to default source sets.
2. Add to dependencies of default source sets.
3. Add to compile task directly, e.g., via AbstractCompile.source
KSP picked up from the first 2 only. Now it also does third.

Allowing getting sources from compile tasks

---

README.md

https://github.com/line/lich/tree/master/savedstate#lich-savedstate
Lich SavedState is a library that provides type-safe access to saved instance state.
Now, it officially supports KSP to generate arguments classes for the saved instance state.

Add Lich SavedState to supported libraries.

---

README.md

[gRPC Dekorator](https://github.com/mottljan/grpc-dekorator) is a library that you can use to decorate your RPCs to add them some special functionality which is not possible using gRPC's ClientInterceptors. It generates decorator classes using KSP.
I would also like to appreciate and thank you for your amazing job on KSP!

Add gRPC Dekorator to supported libraries

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/CheckOverrideProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/GetSymbolsFromAnnotationProcessor.kt
compiler-plugin/testData/api/getSymbolsFromAnnotation.kt

fixes #636 
also handled the annotation use site target for constructor parameter. note that with such handling logic, 2 symbols will be returned (one for property declaration and one for value parameter) for a property declared in primary constructor, unless `@param` is specified.

fix getSymbolsWithAnnotation for @setparam and @param use site target

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/KspIntegrationTestRule.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestModule.kt
integration-tests/src/test/resources/incremental/workload/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/playground-mpp/workload/build.gradle.kts

This PR introduces sourceSet specific gradle configurations for multiplatform users, so that ksp processors can be applied selectively to only one target, for example. Relevant discussion: https://kotlinlang.slack.com/archives/C013BA8EQSE/p1630359069041200
- Root configuration `ksp` incorrectly? applied to everything
- Source set configurations `ksp<Set>` available only in single-platform projects (like kotlin-jvm)
- Android treated as a special case, creating `ksp<Set>` configurations from AGP `AndroidSourceSet`s, but without dedicated logic when picking up the correct configurations to apply to a given compilation.
- <strike>Root configuration `ksp` is applied to main sets of all targets - does not apply to test compilations anymore</strike> 
- **Single-platform projects** (like …

Enable multiplatform configurations

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt

So that the behavior aligns with KSP 1.0.0. Note that the apply-to-all
`ksp` configuration is being deprecated in the following way:
1. A seperate `kspTest` configuration is available for test source
sets now. In the future `ksp` won't apply to test source sets.
2. `ksp` will not be available at all for multiplatform projects.
The `ksp.allow_all_target_configuration` gradle property is also
introduced, so that users can early-access the new behavior by setting
it to false.

Re-include the `ksp` dependency for all targets

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml

Don't merge before the branch is renamed.

Update CI for the kotlin-1.6.0 -> 1.0.1-release rename

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/AnnotatedUtilProcessor.kt
compiler-plugin/testData/api/annotatedUtil.kt
compiler-plugin/testData/api/javaAnnotatedUtil.kt

- add support after blocking issue https://github.com/google/ksp/issues/53 was fixed
- remove NPE catch
- add tests for default KClass and Class for getAnnotationsByType
- handle Java Class default value retrieval using reflection for PsiImmediateClassType

Add support for default Class or KClass values

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassifierReferenceLiteImplForJava.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceLiteJavaImpl.kt
compiler-plugin/testData/api/libOrigins.kt
compiler-plugin/testData/api/parent.kt

also fixes #707 
verified locally with a resolve counter to verify that total resolve call has reduced with this change, unable to add a test due to the need to add debug code into implementation code. The test here reflect the correct `KSClassifierReference` has been populated for the missing cases.

support referenced element for KSTypeReferenceLiteJavaImpl

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/VersionCheckIT.kt

ApiVersion is used and implemented by Kotlin compiler.
VersionNumber is deprecated.
Fixes #723

Parse and compare Kotlin version by ApiVersion

---

README.md

As of 2.8.0 [RxHttp](https://github.com/liujingxing/RxHttp) has official KSP support

Update RxHttp in the README.md

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/resources/kmp/workload/build.gradle.kts

When `js(BOTH)` is used, we map `jsLegacy` and `jsIr` to `js` because both of the compiler created targets share the same source set. For simplicity and consistency, let's not distinguish the two targets when creating and specifying KSP configurations.
The mechanism of generating binary (or js) directly from processors is undefined yet.

Supported js(BOTH) and disallow binary generation for non-JVM targets

---

README.md

It's officially supported now https://github.com/square/moshi/blob/master/CHANGELOG.md#version-1130

Update Moshi support status

---

kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ProjectStructureProviderImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileSymbolImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSNameImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/testData/api/hello.kt

* All KSSymbols skeleton.
* use same bootstrap version for compiler and analysis api.
* implemented some no resolution involved KSSymbol functions, many are still missing, e.g. modifiers conversion (this should be able to be reused from current frontend implementation).
* implemented simple resolution logic as analysis api resolution concept proofing. 
* Note that analysis API unifies symbols implementation, so there is no need to have 3 implementations for java symbols, kotlin symbols, and descriptor symbols anymore, however, for certain functions, we still need to type check the wrapped element inside a KtSymbol and performance operations accordingly.

Analysis API implementation

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/backingFields.kt

This PR fixes a bug where KSP fails to find a backing field for a property that is set from an explicit constructor.
I couldn't find anything in KtProperty that would give me this information so I fall back to the descriptor implementation. Assuming that is more expensive, I still kept the existing checks for faster resolutions.
Also added a minor change for the descriptor path to check for lateinit or abstract before checking the .class file which should be faster

Fix backing fields for properties that are set from an explicit constructor

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/AbstractFunctionsProcessor.kt
compiler-plugin/testData/api/abstractFunctions.kt

Before this CL the method originating from Java interface was presumed abstract
if not marked `default`. This is not entirely correct, as static methods are also
not abstract. This CL fixes the issue.

#775: Take `static` into account when computing `isAbstract` for java.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Some targets, like js(LEGACY) and js(IR), may share source sets.

Split output and cache directories by target

---

.github/workflows/auto-merge.yml

Some commits are compiler version specific and they don't touch
third_party/prebuilt/repo. They shouldn't be picked automatically into
release branches.

auto-merger: don't pick commits in DONT_PICK

---

kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

Besides providers (#802, #804, and #809), there are static/upstream versions of provider factories too. We can avoid registering anonymous objects.

FIR: use upstream static provider factories

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

KSP for FIR is still under development. This change allows KSP to be
used with compiler tasks where FIR is enabled.

Unconditionally disable FIR in KSP Gradle tasks

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

KSP for FIR is still under development. This change allows KSP to be
used with compiler tasks where FIR is enabled.
(cherry picked from commit b5867e6af5e30193d7a11c6ee39262c0cba193ab)

cherry-pick: Unconditionally disable FIR in KSP Gradle tasks

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaEnumEntryImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ReplaceWithErrorTypeArgsProcessor.kt
compiler-plugin/testData/api/replaceWithErrorTypeArgs.kt

Cases are:
* #arguments doesn't match
* There are error types in arguments

Handle more errors when replacing type arguments

---

api/src/main/kotlin/com/google/devtools/ksp/processing/PlatformInfo.kt
api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessorEnvironment.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/PlatformInfoImpl.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt

New APIs:
```
class SymbolProcessorEnvironment(
...
val apiVersion: KotlinVersion,
val compilerVersion: KotlinVersion,
val platforms: List<PlatformInfo>,
}
```
Also fixed `SymbolProcessorEnvironment.kotlinVersion` to return language version instead of some random compiler version.

APIs for api/compiler versions and target info

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalRemovalIT.kt
integration-tests/src/test/resources/incremental-removal/build.gradle.kts
integration-tests/src/test/resources/incremental-removal/gradle.properties
integration-tests/src/test/resources/incremental-removal/settings.gradle.kts
integration-tests/src/test/resources/incremental-removal/validator/build.gradle.kts
integration-tests/src/test/resources/incremental-removal/validator/src/main/kotlin/Validator.kt
integration-tests/src/test/resources/incremental-removal/validator/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/incremental-removal/workload/build.gradle.kts
integration-tests/src/test/resources/incremental-removal/workload/src/main/kotlin/p1/K1.kt
integration-tests/src/test/resources/incremental-removal/workload/src/main/kotlin/p1/Main.kt

Output files that disappeared in previous compilation can also
participate in dirtyness propagation and should only be removed after
calculating the dirty set.
fixes #767

Defer some updates of symbol and lookup tables

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/EquivalentJavaWildcardProcessor.kt
compiler-plugin/testData/api/equivalentJavaWildcards.kt

by resolving the containing reference that is not a part of type arguments, and then locate the reference of interest.

getJavaWildcard: fix cases for nested type args

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/JavaWildcard2Processor.kt
compiler-plugin/testData/api/equivalentJavaWildcards.kt
compiler-plugin/testData/api/javaWildcards2.kt

@JvmSuppressWildcards can be inherited from containing declarations or
types.
@JvmWildcard only applies to the immeidate type.
Fixes #773

getJavaWildcard: fix annotation search

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ConstPropertiesProcessor.kt
compiler-plugin/testData/api/constProperties.kt

Before this CL, `CONST` modifier was present only in
`KSPropertyDeclarationImpl` for `const` properties.
`KSPropertyDeclarationDescriptorImpl` lacked this modifier for
the same property when deserialized from compiled code.
This CL fixes the inconsistency.

#850: Recover `CONST` modifier in descriptor-based property impl.

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/DeclarationUtilProcessor.kt
compiler-plugin/testData/api/declarationUtil.kt

This CL fixes a bug in in KSP where we were marking nested
classes as public by mistake (the code seems to focus on
properties and methods of interfaces).
To keep a similar logic, I just excluded KSClassDeclarations
from that check.
I've also updated the test to be a bit more readable to only
list properties that return true.
Fixes: #876
Test: declarationUtil.kt

Don't mark nested classes as open

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OnlyResourcesFileIT.kt
integration-tests/src/test/resources/only-resources-file/build.gradle.kts
integration-tests/src/test/resources/only-resources-file/settings.gradle.kts
integration-tests/src/test/resources/only-resources-file/test-processor/build.gradle.kts
integration-tests/src/test/resources/only-resources-file/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/only-resources-file/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/only-resources-file/workload/build.gradle.kts
integration-tests/src/test/resources/only-resources-file/workload/src/commonMain/kotlin/MyStub.kt

Create Kotlin output dir during analysis

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OnlyResourcesFileIT.kt
integration-tests/src/test/resources/only-resources-file/build.gradle.kts
integration-tests/src/test/resources/only-resources-file/settings.gradle.kts
integration-tests/src/test/resources/only-resources-file/test-processor/build.gradle.kts
integration-tests/src/test/resources/only-resources-file/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/only-resources-file/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/only-resources-file/workload/build.gradle.kts
integration-tests/src/test/resources/only-resources-file/workload/src/commonMain/kotlin/MyStub.kt

1.0.5-release is still on Kotlin 1.6.10 and doesn't have `kspCommonMainMetadata`.

Cherry pick #875 manually

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RawTypesProcessor.kt
compiler-plugin/testData/api/rawTypes.kt

This is required for checking if the underlying type is Java's raw type.
Such information is sometimes required to correctly override Java methods
while generating Java code.

#851: Add isJavaRawType function to Resolver.

---

CONTRIBUTING.md
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
integration-tests/src/test/resources/playground-android-multi/application/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/settings.gradle.kts
integration-tests/src/test/resources/playground-android-multi/workload/build.gradle.kts
integration-tests/src/test/resources/playground-android/build.gradle.kts
integration-tests/src/test/resources/playground-android/settings.gradle.kts
integration-tests/src/test/resources/playground-android/workload/build.gradle.kts
settings.gradle.kts

Hey, a small PR to fix a personal bug bear of mine.
Using `jcenter()` raises deprecation warnings in Gradle https://blog.gradle.org/jcenter-shutdown
I also fixed a couple of minor warnings and a couple of typos.
I can't build the project locally (see error below), so if this PR is more trouble than it's worth then feel free to reject it 👍 
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':common-util:instrumentCode'.
> D:\Users\...\scoop\apps\microsoft11-jdk\current\Packages does not exist.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
18:40:54: Execution finished 'build'.
``` …

Remove jcenter() from Gradle repositories

---

benchmark/TachiyomiExhaustive/upload-benchmark-data.sh
benchmark/runner/runner.sh

Minor tweaks to runner and benchmark data build scripts.
Benchmark runner can now be used in the ksp repo with just the
benchmark name as the argument:
`./benchmark/runner/runner.sh TachiyomiExhaustive`

Add script to upload benchmark data.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/kmp/workload-linuxX64/src/linuxX64Main/kotlin/ToBeRemoved.kt

In other platforms, outputs are deleted in AbstractKotlinCompile, which
is not inherited by K/N.

K/N: delete outputs upfront

---

.github/workflows/auto-merge.yml

which is already picked, but somehow the hash in commit message is
wrong.

auto-merge: don't pick d6f2b6eef0

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/testData/api/typeAlias.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeAliasProcessor.kt

This PR fixes a problem in KSType where it was not returning the right type arguments for TypeAliases.
For input:
```
typealias MyList = MyList<Int>
val x: MyList = TODO()
```
Querying the typeArguments of `x` would return `[Int]` while also returning its declaration as `MyList`.
This makes it looks like `MyList<Int><Int>`.
To fix it, I updated `KSType.arguments` to use the abbreviation type instead of the KotlinType.
Also, updated the test to add more cases and make it print the arguments for each type. I refactored the
test a bit to print types of properties instead of all found types to make the output more readable (happy to revert that part).
Fixes: #881
Test: typeAlias.kt

Use abbreviation when returning arguments for a KSType

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
compiler-plugin/testData/api/javaSubtype.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JavaSubtypeProcessor.kt

Compiler subtype checking does not convert Java types to Kotlin types, while getting super types from a java type does the conversion, therefore resulting in subtype checking for Java types to fail.
Check if candidate super type is a Java type, convert to Kotlin type for subtype checking.
Potentially needs an ultimate fix in compiler for subtype checking.
fixes #890

Fix subtype checking for Java types.

---

gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/KspIntegrationTestRule.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestProject.kt

This allows one to configure the KspExtension with a CommandLineArgumentProvider.
Inputs and outputs can now properly declared on any additional input or output directories to the KSP compilation.
Fixes #847
Note: this also upgrades the Room dependency to 2.4.2 across the project since 2.3.0 does not support KSP.

Add CommandLineArgumentProvider

---

.github/workflows/auto-merge.yml

where compiler bump commits should come from origin/main, instead of
current branch.
Tested locally.

Fix auto-merge

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt

* implement KSClassDeclaration for KtEnumEntrySymbol
* implement getClassDeclarationByName
* some refactoring to common logics.
tested with `KSPAATest.testClassKinds`, passed test for non-Java symbols.
Expected
```
JA: ANNOTATION_CLASS
JC: CLASS
JE.ENTRY: ENUM_ENTRY
JE: ENUM_CLASS
JI: INTERFACE
KA: ANNOTATION_CLASS
KC: CLASS
KE.ENTRY: ENUM_ENTRY
KE: ENUM_CLASS
KI: INTERFACE
KO: OBJECT
kotlin.Annotation: INTERFACE
kotlin.Any: CLASS
kotlin.Deprecated: ANNOTATION_CLASS
kotlin.DeprecationLevel.WARNING: ENUM_ENTRY
kotlin.DeprecationLevel: ENUM_CLASS
kotlin.Double.Companion: OBJECT
```
Actual
```
KA: ANNOTATION_CLASS
KC: CLASS
KE.ENTRY: ENUM_ENTRY
KE: ENUM_CLASS
KI: INTERFACE
KO: OBJECT
kotlin.Annotation: INTERFACE
kotlin.Any: CLASS
kotlin.Deprecated: ANNOTATION_CLASS …
```

Class kind AA implementation 

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/testData/api/sealedClass.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/SealedClassProcessor.kt

fixes #936 
Cause is that we did not check the psi for the sealed sub classes descriptors.
Testing `toLocation()` is not possible in our test infrastructure, hence test the origin instead, when origin is `KOTLIN` there will be a location value from the psi.

try to get psi before creating sealed sub class declarations

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSValueParameterDescriptorImpl.kt
compiler-plugin/testData/api/allFunctions.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AllFunctionsProcessor.kt

compiler implementation of `isVararg` is essentially checking `varargElementType != null`.
fixes #958

use correct type for vararg value parameter descriptor implementation

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/VerboseIT.kt

* Logs current round number of processing.
* Logs loaded providers.
* Logs an error when there is no providers found in AP classpath.
fixes #927 
also fulfills a providers related logging request from Donald.

First verbose mode support.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt

fixes #948 
VirtualFile does not seem to return the true path even though the Javadoc of `canonicalPath` says so, therefore using system API to fix it.
Tested locally with androidx reproduce repo, can't find a good way to reproduce within KSP's test framework.

invoke system file API to get true path for symbol links

---

api/build.gradle.kts

flag `compatibility ` has been deprecated since 1.5.0
https://kotlinlang.org/docs/whatsnew15.html#deprecation-of-jvmdefault-and-old-xjvm-default-modes

replace deprecated compatibility jvm-default flag with all-compatibility

---

.github/workflows/release.yml
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt

Previous symbolic link fix is causing issues for incremental on Windows, disabling this fix for Windows for now.

disable symbol link check on Windows

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
compiler-plugin/testData/api/lateinitProperties.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/LateinitPropertiesProcessor.kt

Very similar to what I did with `const` modifier once.

Recover `lateinit` modifier for descriptor-based implementations.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt

Sometimes raw types may be wrapped into "enhanced" types by the compiler,
so the old naive check didn't work on them.
`UnwrappedType`'s doc states, that it's only safe to use `instanceof` checks on unwrapped types.
I ran into this issue in my closed-source project yet was unable to reproduce it with KSP testing infra,
so no test changes here.

`KotlinType.unwrap()` has to be used for correct `is` checks.

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt

I've found a bug in method `KSAnnotation.getAnnotationsByType` when trying to access class field of annotation.
**For example**, we have custom class and custom annotation that takes this class as a parameter declared in module `owner-api`: 
```kotlin
interface CodeOwner
object KspTeam : CodeOwner
annotation class OwnerAnnotation(val clazz: KClass<out CodeOwner>)
```
And processor which simply logs code owners is declared in module `owners-processor`:
```kotlin
class OwnerProcessor(private val logger: KSPLogger) : SymbolProcessor {
@OptIn(KspExperimental::class)
override fun process(resolver: Resolver): List<KSAnnotated> {
resolver.getSymbolsWithAnnotation("com.example.processor.OwnerAnnotation")
.forEach {
val annotation = it.getAnnotationsByType(OwnerAnnotation::class).first() …
```

Support class extraction provided by annotation

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/javaSubtype.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JavaSubtypeProcessor.kt

E.g. a `kotlin.Function0` type is a Kotlin "fictional" type;
the real JVM type it is backed by for JVM is `kotlin.jvm.functions.Function0`.
Inside the compiler the backing type is always converted into Kotlin's one.
Yet for KSP the `kotlin.jvm.functions.Function0` with its deserialized descriptor
can be obtained directly (e.g. via `getJavaClassByName`) and used along with
the `kotlin.Function0` type.
This CL fixes the assignability check between such types.

Fix assignable check for function types with deserialized descriptors.

---

settings.gradle.kts

The current failing auto-merge action is caused by an incompatible change in analysis API, our build script applies same kotlin version across the repo. As we are not releasing analysis API implementation yet, disable AA module on release branch to unblock auto-merge.

disable analysis api module on release branch

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/JavaNestedClassIT.kt
integration-tests/src/test/resources/javaNestedClass/build.gradle.kts
integration-tests/src/test/resources/javaNestedClass/settings.gradle.kts
integration-tests/src/test/resources/javaNestedClass/test-processor/build.gradle.kts
integration-tests/src/test/resources/javaNestedClass/test-processor/src/main/kotlin/ValidateProcessor.kt
integration-tests/src/test/resources/javaNestedClass/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/javaNestedClass/workload/build.gradle.kts
integration-tests/src/test/resources/javaNestedClass/workload/src/main/java/com/example/A.kt
integration-tests/src/test/resources/javaNestedClass/workload/src/main/java/com/example/JavaClass.java

This is a temporary workaround for https://github.com/google/ksp/issues/1034
fixes #1034

Force resolve outermost class for Java nested classes.

---

compiler-plugin/testData/api/errorTypes.kt
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KSPCommandLineProcessor.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

I am open to suggestions on the error type test. Basically AA is capable of resolving a function call with error argument, which actually makes more sense to me, but at this point it might not make a lot of sense to fix old frontend (assume changes in upstream). 
An alternative is to have 2 versions of test result for comparing, as we are expecting more inconsistency between old and new frontend, this also makes sense in terms of long term investment.

AA: use AAsession, test infra fix, error type fix

---

common-util/src/main/kotlin/com/google/devtools/ksp/KspOptions.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt

This option will allow users to specify certain processors(s) to be
executed, if not specified, all processors found in apclasspath will be
executed.

introduce processorName option for KSP.

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileJavaImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

* fixes super types for enum entry.
* unmute classKind test.

AA: use KtSymbolProviderByJavaPsiMixIn for converting PSI class to AA symbols.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSFunctionDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaEnumEntryImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSPropertyDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceLiteJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSAnnotationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSExpectActualImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyGetterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertySetterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeReferenceImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSErrorTypeClassDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSPropertyGetterSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSPropertySetterSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt

by keeping static variables as few as possible, and set them to null after each round.
See #1063 for details.

A mitigation for processors with memory leaks

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
compiler-plugin/testData/api/allFunctions_java_inherits_kt.kt
compiler-plugin/testData/api/allFunctions_kotlin.kt
compiler-plugin/testData/api/allFunctions_kt_inherits_java.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

* getAllSymbols returns all symbols including invisible ones, check vibility for the target class to filter out unneeded symbols.
* Include a temporary workaround for checking containing class due to FIR compiler limitation.
* unmutes allFunctions_kotlin allFunctions_java_inherits_kt test.

AA: add visibility check for getAllFunctions/getAllProperties 

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
compiler-plugin/testData/api/getAnnotationByTypeWithInnerDefault.kt
compiler-plugin/testData/api/getByName.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/GetAnnotationByTypeProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/GetByNameProcessor.kt

* fixes #989
The root cause might be in compiler, as the compiler returns a `NotFoundClasses` for nested annotation types.

manually look up in scope when annotation argument type is nested annotation.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
compiler-plugin/testData/api/functionTypeAnnotation.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/FunctionTypeAnnotationProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/FunctionTypeProcessor.kt

fixes #985 
several open questions:
* defining annotations origin for KSType is tricky, as type is not part of source code. with this PR actually all annotation origins from KSType becomes library, which I actually found more meaningful, but this can be breaking change.
*  since `KotlinType.annotations` contains the full picture of the actual annotations of a kotlin type, the `annotations` parameter in `getKSTypeCached` is no longer necessary, might want to clean up in a future patch.

retrieve annotations for KSType from KotlinType instead of KSTypeReference

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSErrorType.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ParameterTypeProcessor.kt
test-utils/testData/api/parameterTypes.kt

* fixed rendering logic for error types and flexible types.
* fixed origin for kotlin synthetic property accessors.
* unmuted implicitElements implicitPropertyAccessors javaTypes makeNullable parameterTypes tests.

Unmutes more single module tests for analysis API.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeReferenceDescriptorImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/InheritedTypeAliasProcessor.kt
test-utils/testData/api/inheritedTypeAlias.kt

Use abbreviated type for creating reference elements from inherited declarations.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceJavaImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JavaNonNullProcessor.kt
test-utils/testData/api/javaNonNullTypes.kt

* for referenced java types, compiler already handles nullability annotations.
* fixes #167

respect nullability annotations on Java type references.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

and deprecate `blockOtherPlugins`.
Fixes #897 
There's still no real test yet because no built-in plugin runs before `AnalysisHandlerExtension`; The existing test only checks whether it builds.

Block other compiler plugins by default

---

common-util/src/main/kotlin/com/google/devtools/ksp/KSPUtils.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeArgumentDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSTypeReferenceDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSTypeReferenceSyntheticImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSCallableReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassifierReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSDynamicReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeAliasImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeAliasComparisonProcessor.kt
test-utils/testData/api/typeAlias.kt
test-utils/testData/api/typeAliasComparison.kt

* Handled type aliases better 
* Added parent information to some non source based KtSymbols 
* Added more rendering logic for types
* Use the correct object cache for type references.
This is not a final implementation for some of the added classes, some of the TODOs will be addressed in a follow up PR, to avoid too large PR.
TODOs:
* should use `KtTypeReference` as the wrapping element for kotlin source based type references.
* AA actually returns type annotations in more scenarios compared to FE 1.0 causing nestedClassType test to fail, need to address it in a way that tests framework should be able to handle 2 sets of expected results.
* The current ClassifierReference implementation still has some way to go in terms of correctness.

AA: type alias and reference elements.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KotlinConstsInJavaIT.kt
integration-tests/src/test/resources/kotlin-consts-in-java/build.gradle.kts
integration-tests/src/test/resources/kotlin-consts-in-java/settings.gradle.kts
integration-tests/src/test/resources/kotlin-consts-in-java/test-processor/build.gradle.kts
integration-tests/src/test/resources/kotlin-consts-in-java/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/kotlin-consts-in-java/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/kotlin-consts-in-java/workload/build.gradle.kts
integration-tests/src/test/resources/kotlin-consts-in-java/workload/src/main/java/com/example/JavaClass.java
integration-tests/src/test/resources/kotlin-consts-in-java/workload/src/main/java/com/example/KotlinConsts.kt
integration-tests/src/test/resources/kotlin-consts-in-java/workload/src/main/java/com/example/ann/MyAnn.kt

so that constants in light classes can be resolved by JavaPsiFacade.
Fixes #997.

Scan Kotlin constants for JavaPsiFacade

---

kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

to unblock windows CI before determine the root cause.

temporary disable AA tests on Windows

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/synthetic/KSSyntheticAnnotations.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

* fixed isFunctionType check for KSType
* fixed `@ExtensionFunctionType` annotation on extension function types.
* added additional checks for checking interface properties with default implementations.

minor fixes to types and util

---

common-util/src/main/kotlin/com/google/devtools/ksp/DescriptorUtils.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
integration-tests/src/test/resources/javaNestedClass/test-processor/src/main/kotlin/ValidateProcessor.kt
integration-tests/src/test/resources/javaNestedClass/workload/src/main/java/com/example/JavaClass.java

By mapping PSIs from SourceElements to PSIs loaded by KSP.
PSIs from descriptors are different instances than PSIs from KSFileJavaImpl. Although they are structurally equivalent, `equals` returns false.

Fix DeclarationDescriptor.findPsi

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/DefaultFunctionProcessor.kt
test-utils/testData/api/interfaceWithDefault.kt

* also includes a fix to Java psi modifier for AA.
fixes #1153

final Java fields should not be mutable.

---

settings.gradle.kts

This recommended practice also removes a warning in certain cases involving composite builds.

Explicitly set root project name

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt

This PR proposes a solution for the issue explained in #1167
CommandLineArguments are included as SubpluginOptions through the KspExtension. With this change, we include the CommandLineArguments from the KspTask allowing ad-hoc configurations for arguments in the task:
```kotlin
tasks.withType<KspTask>().configureEach {
commandLineArgumentProviders.add(Provider(project.layout.projectDirectory.dir("schemas-${name}").asFile))
}
```

Including CommandLineArgument as SubpluginOption with KspTask

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

there is some code copied with minor modification from FE1.0 implementation, unfortunately not reusable due to relying on implementation details, with more similar case discovered, it is also worth considering how to better abstract common logics.

AA: support use site annotations

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

also includes additional works to get modifiers for library symbols since they have no psi at this time. Ideally library symbols should also have PSI but it can be either expensive (likely building a stubs with more details not needed for KSP) or take a long time to be available, therefore put the current logic in place.

AA: getDeclarationsFromPackage 

---

api/build.gradle.kts
gradle-plugin/build.gradle.kts
symbol-processing-cmdline/build.gradle.kts
symbol-processing/build.gradle.kts

Now, instead of specifying keyring and key id in gradle.properties:
```
$ export ORG_GRADLE_PROJECT_signingKey=$(gpg --export-secret-keys --armor)
$ export ORG_GRADLE_PROJECT_signingPassword=...
```

Sign with in-memory pgp keys

---

build.gradle.kts

so that `kspVersion` can be constructed by
`"$kotlinBaseVersion-$kspOnlyVersion"`
where `kotlinBaseVersion` is available in gradle.properties.

Introduce `kspOnlyVersion` to root build script

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
kotlin-analysis-api/testData/innerTypes.kt

For functional type, resolve type aliases in type arguments to align with FE1.0 behavior.
For star projected type, use a separate test data, as the behavior mismatches.

fix function type alias and star projected type

---

api/build.gradle.kts
common-util/build.gradle.kts
compiler-plugin/build.gradle.kts
gradle-plugin/build.gradle.kts
kotlin-analysis-api/build.gradle.kts

Fixes building with JDK 17.
Without this, my build fails with:
```
> Task :api:dokkaJavadoc
Initializing plugins
Dokka is performing: documentation for api
Validity check
Creating documentation models
ERROR: Exception while analyzing expression at (294,45) in /Users/mbonnin/git/ksp/api/src/main/kotlin/com/google/devtools/ksp/utils.kt
org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Exception while analyzing expression at (294,45) in /Users/mbonnin/git/ksp/api/src/main/kotlin/com/google/devtools/ksp/utils.kt
at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:246)
at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:2 …
```

Bump dokka to 1.7.20

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt

Register autogenerated kotlin source files to android plugin source set for IDE/AndriodStudio indexing

Android Gradle Plugin: add generated kotlin sources 

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

In FIR java types are first resolved to `JavaTypeRef` which is incompatible with `FirResolvedTypeRef` used in `FirCallableSymbol.returnType` whichj is in turn used by AA for getting symbol return types.
In FIR, java symbols are constructed to default be in last FIR resolve phase, therefore trying a workaround where we manually convert the java type refs `o` resolved type refs with internal functions from fir.java module should be safe for KSP.
Using this workaround before upstream fixes this issue

AA java refs workaround

---

api/build.gradle.kts
buildSrc/build.gradle.kts
common-util/build.gradle.kts
compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
gradle-plugin/build.gradle.kts
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestProject.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSCallableReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassifierReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
test-utils/build.gradle.kts

changes involved:
* compiler has made `kotlin.jvm.target.validation.mode` default to error, set the flag explicitly to `warning`, but seems to not work for buildSrc, since KSP build requires JDK 11 for android tests, it is better to just change buildSrc to use JDK11.
* compiler is now built with `-Xjvm-default=all`, KSP need to adopt all other occurrences of jvm default build flag to ensure run time works.
* some adjustments in analysis API to align with upstream changes, namely changes in how inner type arguments and complete type arguments are handled, now `KtType` will only contain innerTypeArguments, therefore we need to look up the newly added `qualifiers` to get the complete list of type arguments.

UPDATE_KOTLIN_VERSION: 1.8.20-dev-2904

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
test-utils/testData/api/annotationInDependencies.kt

This special handling is needed when an annotation has implicit use site
target restriction declared at that annotations declaration site. This is
only happening for properties declared in constructor parameter because in
constructor parameter, the use site is value parameter which does not violate
annotation target contract, and annotations gets carried over to its actual
property, therefore need to read the annotation declaration and resolve for targets.
The logic is unfortunately, ugly, wonder if there is any utility functions to check it simpler.
fixes #1198

Handle AnnotationTarget.VALUE_PARAMETER for property declarations.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt

Fixes https://github.com/google/ksp/issues/1218

Add args from `CommandLineArgumentProvider` as separate `apoption` instead of joined.

---

gradle.properties

Kotlin 1.8.0-RC2 and 1.8.0 are based on exactly the same commit.

UPDATE_KOTLIN_VERSION: 1.8.0

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/OverrideeProcessor.kt
test-utils/testData/api/overridee.kt

fixes #1182
The issue has been observed before in other implementations, somehow the fix missed `KSPropertyDeclarationParameterImpl`

use correct overridee check for properties declared in constructors.

---

common-util/src/main/kotlin/com/google/devtools/ksp/KspOptions.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Excluded providers won't be called, even if they are loaded from classpath. This makes it easier to write wrappers for processors.
Fixes #1234

Add extension: excludeProcessor()

---

common-util/src/main/kotlin/com/google/devtools/ksp/KspOptions.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/MapAnnotationArgumentsIT.kt
integration-tests/src/test/resources/map-annotation-arguments/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/map-annotation-arguments/workload/src/main/java/com/example/AnnotationTest.java
integration-tests/src/test/resources/map-annotation-arguments/workload/src/main/java/com/example/JavaAnnotation.java

which defaults to false. When enabled, annotation arguments are mapped to Kotlin types in Java source files.
The option will be flipped to true and deprecated in the future gradually.
fixes #870

Introduce ksp.map.annotation.arguments.in.java

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/resources/incremental/workload/build.gradle.kts

KGP doesn't register FilesSubpluginOption nor InternalSubpluginOption.
Fixes #1308

Register processor classpath to Gradle

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AGP741IT.kt

AGP doesn't like it being resolved during configuration time.
Fixes #1294

Defer resolution of processor classpath

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

updating to latest compiler bootstrap.
Main changes: Kotlin/Native gradle task moved compiler options into constructor, added requirement for `moduleName`, changed accordingly in KSP gradle plugin.
Muted annotationOnConstructorParameter test for AA for now, reason: after this update, analysis API is no longer returning annotations on properties declared in constructor at least for the case declared in this test, need to figure out what's the cause afterwards.

UPDATE_KOTLIN_VERSION: 1.9.0-dev-2695

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
test-utils/testData/api/javaAnnotatedUtil.kt

To fix https://github.com/google/ksp/issues/1329

Get AnnotationByType's invocation handler supports java array value

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSCallableReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassifierReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSDefNonNullReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSDynamicReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

* reimplement reference element to align with upstream's change to `KtType.qualifiers`
* Support def non null types in reference element
*  tested for symbols from source, symbols from binaries blocked due to get top level callables not working for libraries.
* some other minor fixes.

AA: reference element rework

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt

per the documentation for this property: `Controls whether changes in lookup cache should be tracked. Required for the classpath snapshots based IC approach`

set trackChangesInLookupCache for Incremental context

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIncrementalIT.kt

per comment in #649 , as the [linking issue](https://youtrack.jetbrains.com/issue/KT-45777) has been fixed, we should be able to remove this name mangling logic now.

remove module name mangling workaround

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KSPCmdLineOptionsIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt

Disabled command line integration test for this bootstrap due to binary compatibility issue, this should be reenabled before 1.9.0 release.

UPDATE_KOTLIN_VERSION: 1.9.0-dev-4392

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

We described in https://github.com/google/ksp/issues/1359 a cache issue when using Ksp with the Room processor since version 1.8.10-1.0.9. 
After reviewing the code, we have noticed that since this version all the values of the internal property `options` are set as `CompilerPluginConfig` for the KspTasks.  
```kotlin
kspTask.pluginOptions.add(
project.provider {
CompilerPluginConfig().apply {
(kspTask as KspTask).options.get().forEach {
addPluginArgument(KSP_PLUGIN_ID, it)
}
}
}
)
```
Later,  KGP will populate the inputs arguments like:
```kotlin
result["$subpluginId." + option.key + indexSuffix] = option.value
```
At this point, KGP doesn't know about the path sensitivity of the argument value producing different build cache keys:
(notice the argument …

Marking command line arguments options as InternalSubpluginOptions

---

compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSValueParameterJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KSPCmdLineOptionsIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/kmp/annotations/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-js/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/playground-mpp/workload/build.gradle.kts
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
test-utils/testData/api/parent.kt

2 things needs attention:
* there seem to be a known issue with native embeddable compiler, [fix](https://github.com/JetBrains/kotlin/commit/0fb5934ebd05d0433c9cf2a6ffbdb8269a576b45) in upstream not yet in this version of compiler. Disabling test for now, should get a mitigation if one is easy, or we will be enabling it again if the fix in compiler gets shipped with 1.9.0 (currently the fix is only in 1.9.20-dev- builds).
* The information for java synthetic classifier reference is lost in intellij upgrade, and even trying converting it to kotlin type (i.e. descriptor based solution) can't get the information back. The logic in descriptor looks making more sense to me, tentatively changing the test as a breaking change for this version upgrade.
Let me know any concerns with these 2 items.

UPDATE_KOTLIN_VERSION: 1.9.0-dev-6976

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

`errorType` test now returns a different result which should be discussed separately and disabled for this version update.

UPDATE_KOTLIN_VERSION: 1.9.20-dev-2357

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

instead of relying on `AbstractKotlinCompileConfig`.

Get language version from KotlinCompilation

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

instead of copying them one by one.

Sync compiler options from KotlinCompilation

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeAnnotationProcessor.kt
test-utils/testData/api/typeAnnotation.kt

there is a conflict on the commit 1c588f6de1f7528945d01cf3220aa8c7d3e3de51 needs to be manually resolved. Also `PlayGroundIT.testProjectExtensionCompilerOptions` can't pass unless under 1.9.0-RC version.

fix 1.0.12 release branch & Update to 1.9.0-RC

---

buildSrc/src/main/kotlin/com/google/devtools/ksp/ApiCheck.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt

I ran into these failures while trying to build ksp on my Windows machine:
* `:api:checkApi` failed because of the wrong classpath separator, see https://www.baeldung.com/java-classpath-syntax and https://bugs.openjdk.org/browse/JDK-8262004
* `GradleCompilationTest.commandLineArgumentIsIncludedInApoptionsWhenAddedInKspTask` failed because the output had `\` where `/` was expected.

Fix test failures on Windows

---

common-util/src/main/kotlin/com/google/devtools/ksp/processing/impl/CodeGeneratorImpl.kt
common-util/src/test/kotlin/com/google/devtools/ksp/processing/impl/CodeGeneratorImplTest.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
integration-tests/src/test/resources/javaNestedClass/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/javaNestedClass/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

and copy them back into options.javaOutputDir after processing finished.
This works a stale-cache issue in the compiler for nested classes
around.
See #1434 for details.

Generate Java to a new root in each round

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt

They may appear on platforms other than Gradle.
TEST=on other platforms

Java shadow dir: handle absolute paths

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
test-utils/testData/api/getPackage.kt

Using `getDeclarationsFromPackage` fails if the package contains a compiled `typealias`:
```
java.lang.IllegalStateException: failed to analyze: java.lang.IllegalStateException: Unknown expect/actual implementation
at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
at org.jetbrains.kotlin.codegen.GenerationUtils.compileFilesUsingStandardMode(GenerationUtils.kt:205)
at org.jetbrains.kotlin.codegen.GenerationUtils.compileFiles(GenerationUtils.kt:88)
at org.jetbrains.kotlin.codegen.GenerationUtils.compileFiles(GenerationUtils.kt:73)
at org.jetbrains.kotlin.codegen.GenerationUtils.compileFiles$default(GenerationUtils.kt:67)
at org.jetbrains.kotlin.codegen.GenerationUtils.compileFilesTo(GenerationUtils.kt:61)
at …
```

Fix mapping of TypeAliasDescriptor to KsTypeAlias

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSTypeReferenceJavaImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeArgumentVarianceProcessor.kt
test-utils/testData/api/parent.kt
test-utils/testData/api/typeArgumentVariance.kt

fixes #1456 
It is a little bit messed up regarding flexible type.
By Java specs, array should have a single variance of covariance for its type arguments. However, from kotlin compiler, the said type is resolved to a flexible type with a lower bound of invariant type argument and an upper bound of covariant type argument. It might make sense from kotlinc since invariant is more restrictive hence works for a lower bound. It is just that when compiler is dealing with `KoltinType.arguments`, it only looks at lower bound which causes trouble because the lowerbound argument of an array actually discarded the covariant part.
It might look to be better respect Java spec by making it lower bound covariant as well, but attempting to do that caused a lot of failures elsewhere and trying to work …

fix java array argument variance

---

build.gradle.kts
gradle.properties
integration-tests/build.gradle.kts

After loosing some time debugging why some tests were failing I noticed that tests require Java 11, with some in `:integration-tests:test` also require `JDK_9` to be set up and pointing to a Java 9 installation. These changes declare these requirements.
I also updated jUnit to latest jUnit 4 (4.13.1).

Set up jvm toolchain requirements for tests

---

gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/build.gradle.kts
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KSPConfig.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
settings.gradle.kts
symbol-processing-cmdline/build.gradle.kts
symbol-processing/build.gradle.kts

In short, `KspAATask` loads `symbol-processing-aa`, which is an all-in-one fat jar that has no dependencies except kotlin-stdlib, and runs it in a classloader isolated worker.
Besides incremental processing and multiplatform, there are still quite a few TODOs, such as a caching classloader with a clean classpath, processor options and other configs from KspExtension,  logger, use Gradle's jdk home, etc.
On the launcher, there are, for example, multiple-rounds, deprecating CompilerConfiguration, multiplatform, etc.

Initial implementation of KSP 2 Gradle plugin

---

common-util/src/main/kotlin/com/google/devtools/ksp/IncrementalUtil.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OutputDepsIt.kt
integration-tests/src/test/resources/output-deps/test-processor/src/main/kotlin/TestProcessor.kt

so that it won't break build system's incremental mechanism.

Keep timestamps when copying from java shadows

---

common-util/src/main/kotlin/com/google/devtools/ksp/JvmUtils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
kotlin-analysis-api/testData/javaModifiers.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JavaModifierProcessor.kt

* implement `isJavaRawType`
* implement override checking.
* implements Resolver.effectiveJavaModifiers
* assorted minor fixes around modifers and resolver APIs.
test for effective jvm modifiers are forked due to inconsistent behavior with FE1.0 and the new result from AA looks more right to me.

AA: isJavaRawType, override checking and effectiveJavaModifiers

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
test-utils/testData/api/annotationValue_kt.kt

The Kotlin compiler throws unresolvables away silently.

Fill unresolvables with ErrorTypes in annotation

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/analysisapi/providers/IncrementalKotlinDeclarationProvider.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/analysisapi/providers/IncrementalKotlinPackageProvider.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ConstructorDeclarationsProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/MultipleroundProcessor.kt
test-utils/testData/api/multipleround.kt

and replace StandaloneAnalysisAPISessionBuilder, which hides KotlinCoreProjectEnvironment, which is needed to update KotlinCliJavaFileManagerImpl for new files.

multiple-round: implement incremental providers

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionErrorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
kotlin-analysis-api/testData/nestedClassType.kt

In this PR:
* implements asType and starProjectedType for enum entries
* fillup misc apis on value parameter
* implements getDeclarationByName APIs
* fork test data for nestedClassType test (new behavior seems more correct with type annotation included).
* implement asMemberOf
* currently still not working: 
* function substitution is not working with transitive parameters
* type parameter boundaries not rendered with substitution
* add Any to unbounded type parameter

AA: implement asMemberOf

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ExitCodeProcessor.kt
test-utils/testData/api/exitCode.kt

Most of the changes are refactoring to get rid of the hard to maintain `finished`, `initialized` flags.

Handle errors and call SymbolProcessor.onError()

---

api/api.base
api/build.gradle.kts
build.gradle.kts
buildSrc/src/main/kotlin/com/google/devtools/ksp/ApiCheck.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt

* updated metalava version to 1.0.0-alpha08.
* removed stdlib from api subproject dependency.
* added a flag for integration test to use K2.

Update project JDK to JDK17.

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
kotlin-analysis-api/testData/visibilities.kt
test-utils/testData/api/visibilities.kt

* fill up remaining builtin types not available in fir builtins
* handle default annotation value for java class files
* [FE 1.0] fix synthetic constructor visibility for java package private classes
* AA: fix visibility for synthetic constructors/functions.

Aa visibility

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

Notable changes are:
1. Disabled KSP AA tests on 1.0.13 due to dependency conflicts. The tests are redundant to the main branch.
2. Manually picked #1523, which we should have caught in some previous Kotlin version bumps.

UPDATE_KOTLIN_VERSION: 1.9.20-Beta

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

Sort of reimplementation of [FE1.0](https://github.com/google/ksp/blob/0e1aaaa141d14231fad106f021d81cd1c90f2a67/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt#L515) but in a different way, major difference here is the handling of flexible types, analysis API doesn't provide a replace utility for flexible types so instead of creating flexible types with converted type arguments, comparing the bounds directly to workaround it.

handle java types in subtype checking

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

by naming them explicitly in the code.

Save service providers from ShadowJar's minimize()

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/util/BinaryUtils.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/DeclarationOrderProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/testData/api/declarationOrder.kt

* Mostly copied logic from FE1.0, unfortunately coupled code with FE1.0 implementation
details needs to be rewritten and therefore can't be reused directly as common utils.
* Implemented basic getJvmName for unblocking declaration util implementation.
* Due to the library compilation mechanism difference in 2 frontends, FE1.0 tests generates different binaries than AA tests, which caused synthetic constructors being in difference location in the generated bytecode, and since their location are not standardized, ignore them in test results.

Declaration ordering

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

This leaves a better clue of what went wrong.

KSP2: let exceptions pop through to Gradle

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

KotlinCompilation.source() is deprecated.
(cherry picked from commit fbeec1f5e5eeb74d16096f3fa8f983d2269d0ec1)

cherry-pick to 1.0.13: Add generated source set with new KGP API

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalMultiChainIT.kt
integration-tests/src/test/resources/incremental-multi-chain/processors/src/main/kotlin/Aggregator.kt

outputs of removed outputs should be removed as well, instead of being recovered from cache.
Fixes #1554

Incremental: remove outputs recursively

---

common-util/src/main/kotlin/com/google/devtools/ksp/IncrementalUtil.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PartialCleanIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt
integration-tests/src/test/resources/partial-clean/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/partial-clean/workload/src/main/kotlin/com/example/Bar.kt
integration-tests/src/test/resources/partial-clean/workload/src/main/kotlin/com/example/Baz.kt

One common misuse of incremental APIs is associating a non-root source,
instead of the ones obtained from root functions
(e.g., getSymbolsWithAnnotation), to an output. This non-root source can
be reached and reprocessed even when it is clean. Because it is clean,
it is not available via root functions. As a result, other outputs that
are solely based on it won't be re-generated and is deemed as removed.
Assuming that the processors are deterministic, we are throwing away
outputs from clean inputs, and recovering them from the backup as a
workaround for processors.
Fixes #1555

Incremental: Throw away results from clean inputs 

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt

This PR update KspSubplugin to resolve arguments lazily and also adds a workaround for KonanTarget serialization problem.
These are the 3 issues fixed:
* FilesSubpluginOption: Calling `FilesSubpluginOption("apclasspath", processorClasspath.files.toList())` requires resolving that classpath at configuration time, where it may not necessarily be ready for resolution. Replaced it with a `FileCollectionSubpluginOption` that will resolve it lazily. 
* options.get: Ksp was calling `options.get` at configuration time, which again causes early resolution. Furthermore, it won't change if options are later changed, which is a problem. Changed it to use the provider API.
* configuration cache: KSP has a `task.onlyIf` block to check if the KonanTarget can be compiled on this machine. Unfortunately, …

Avoid resolving classpaths eagerly

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

The compiler plugins are always loaded unconditioanlly regardless of K1 or K2 and causes FirKotlinToJvmBytecodeCompiler to throw. Because there seems no way to load compiler plugins conditionally on language version, we declare the KSP compiler plugin to be K2 compatible while doing nothing if K2 is detected.
Tested locally with a new enough Kotlin compiler.

Be more compatible with K2

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/HmppIT.kt

instead of creating source sets and making default source sets depend on them.
This avoids breaking kotlin.mpp.applyDefaultHierarchyTemplate.
Common source sets are untouched, because otherwise the generated sources for them would be observed by downstream compilations and be inconsistent with current KMP build scheme.
Alternatively, we could add all generated files, common or target, directly to compilation tasks and keep default source sets untouched. The drawback is that generated files won't be seen by IDE. We would have to build IDE plugins and implement our own model builder to register generated files to IDE.
TODO: Add common source sets to their corresponding compilation for the new KMP build scheme.

Add generated files to target source sets

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

which was just re-branched from ToT of main. The old branch is renamed to `1.0.14-release-deprecated`.

Downgrade to Kotlin 1.9.20-RC2 for 1.0.14-release

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt

annotation call resolver: lookup scope before creating one

---

common-util/build.gradle.kts
common-util/src/main/kotlin/com/google/devtools/ksp/PersistentMap.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
gradle-plugin/build.gradle.kts
integration-tests/build.gradle.kts

With one left in TODO: `org.jetbrains.kotlin.incremental.LookupStorage`, which requires more works.

Replace compiler's persistent maps with ours 

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Progressive mode should always be used with latest language version.
Fixes #1612

Turn off -progressive when downgrading from K2

---

common-util/src/main/kotlin/com/google/devtools/ksp/PersistentMap.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt

Note that d44ad7d has two prerequisites that were parts of compiler bumps: 4e408831 and 36751997. The relevant changes were manually picked in 87c3929. Later compiler bumps in this branch can be done reverting d104f84f and 87c3929, and then picking 4e408831, 36751997 and d44ad7d.

Cherry-pick updates to persistent maps

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
test-utils/testData/api/annotationValue_kt.kt

Simply replace `$` in the fqname for local class purpose does not work for escaped special class names, hence do a resolution in first try and then fallback to replacing `$` for local class.

fix special class name resolution for class literal annotation value

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ThrowListProcessor.kt
test-utils/testData/api/throwList.kt

fix java type resolution for checked exception

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeAnnotationProcessor.kt
test-utils/testData/api/typeAnnotation.kt

restore annotations on type alias

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/IncrementalKotlinDeclarationProvider.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

This should address indexing for top level callables.
`additionalRoots` is used for indexing during initialization.

include library roots in declaration provider init

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessorEnvironment.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

To be consistent with apiVersion, only major.minor is used. patch is ignored.
TODO: automatically update after KSP 1 is deprecated.

Introduce SymbolProcessorEnvironment.kspVersion

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/CodeGenerator.kt
common-util/src/main/kotlin/com/google/devtools/ksp/processing/impl/CodeGeneratorImpl.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalCPIT.kt
integration-tests/src/test/resources/incremental-classpath/l1/src/main/kotlin/p1/TopFunc1.kt
integration-tests/src/test/resources/incremental-classpath/l1/src/main/kotlin/p1/TopProp1.kt
integration-tests/src/test/resources/incremental-classpath/validator/src/main/kotlin/Validator.kt

by treating outputs of them sensitive to any changes. The granular way requires knowledge from the each backend and will be implemented in the future.

Incremental: Support top level callables in libs

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

`annotationInDependencies` is disabled in KSP2 which incorrectly adds `@ValueParameterTarget(...)` on a constructor parameter to the corresponding property.
Rather than being introduced by the changes in `KotlinSymbolProcessing.kt`, it looks more like a regression in the Analysis API. Therefore this commit disables it for now.

UPDATE_KOTLIN_VERSION: 2.0.0-dev-14242

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/testData/api/mangledNames.kt

fix jvm name for annotation values

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
kotlin-analysis-api/build.gradle.kts
symbol-processing-aa-embeddable/build.gradle.kts

1. kotlin-stdlib was still included from transitive dependencies.
2. jar validation is now merged into `shadow`

Properly config and validate shadow jars

---

common-util/src/main/kotlin/com/google/devtools/ksp/common/impl/RefPosition.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/javaWildcards2.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

main differences in test data other than ordering: type annotation is missing, return type of constructor differs ( VarianceSubjectSuppressed<R> in KSP1 and VarianceSubjectSuppressed<Any?> in KSP2), should be fixed later.

implement getJavaWildcard for KSP2

---

gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

Reverts google/ksp#1765
Merged into the wrong branch.

Revert "1.0.19 release: Downgrade Kotlin to 2.0.0-Beta4"

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSDeclarationDescriptorImpl.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KSPCmdLineOptionsIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Most of the update commits have no changes to compiler-plugin nor gradle-plugin and are skipped.

1.0.18 release: Downgrade Kotlin to 1.9.22

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/testData/visibilities.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/VisibilityProcessor.kt
test-utils/testData/api/visibilities.kt

test result is only modified for KSP2 for the reason that KSP2 treats Java annotation values as properties while KSP1 treats it as functions, therefore the test processor does not look into Java annotation values in KSP1.
One change to shared logic: `isOpen()` should always check for `FINAL` modifier first, this hasn't been an issue for KSP1 since certain synthetic members of data class (namely `componentX`) is not generated in KSP1, but ran into issue with KSP2 where the `OVERRIDE` modifier present in `componentX` take over the `isOpen` check.

fix modifier calculation for synthetic members

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KaptKspTest.kt

This is a workaround for KAPT and KSP work together. 
kotlinCompilation.androidVariant.getSourceFolders(SourceKind.JAVA) is the place both kapt and ksp put result to in order to be available for Kotlin compiler. Still, it causes circular dependency of Gradle tasks like:
```
:app:kaptDebugUnitTestKotlin
\--- :app:kaptGenerateStubsDebugUnitTestKotlin
\--- :app:kspDebugUnitTestKotlin
\--- :app:kaptDebugUnitTestKotlin (*)
```
Fix filters out generated KAPT folder to be input of KSP task.
Unfortunately, there is no API that allow to parallelize such Kotlin preprocessors.

Fix circular dependency with KAPT

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

This new property allows users to create a Gradle task that generates Kotlin code, which can then get excluded by KSP's processing step.
This can help avoid circular Gradle dependency issues, such as in the case where KSP generates an intermediate file (like a resource) which a Gradle plugin then consumes and uses to generate its own Kotlin source.
Without this change, KSP would want to rerun when the new source got generated, which upsets Gradle because it already ran.
The following is one example of using the `excludedSources` property:
```kotlin
val generateCodeTask = tasks.register("generateCodeTask") {
val outputDir = project.layout.buildDirectory.dir("generated/src")
outputs.dir(outputDir)
doLast {
/* ... generate code into outputDir ... */
}
} …
```

Add `excludedSources` to the KSP extension object

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSClassifierReferenceResolvedImpl.kt
kotlin-analysis-api/testData/parent.kt
kotlin-analysis-api/testData/referenceElement.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/testData/api/referenceElement.kt

fallback to resolved types for creating reference element when the type is not supported in PSI element. Tests forked mainly due to behavior change in `toString()` implementation on the reference element, new behavior is more consistent and contains more information.

fix reference element for unhandled types

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/IncrementalContextAA.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/IncrementalKotlinDeclarationProvider.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/KspStandaloneDirectInheritorsProvider.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

also contains changes in AA to unblock sealed subclasses lookup.

UPDATE_KOTLIN_VERSION: 2.0.0-dev-19480

---

kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

1. warn on missing dependencies when building KSP2 uber jar.
2. Add org.jetbrains:annotations
3. do not minimize lz4-java, where some of the classes are loaded by reflection
4. keep more classes by naming them explicitly

Check and add missing dependencies

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

which should be supplied by JDK.

Remove dep to javax.annotation.ParametersAreNonnullByDefault

---

gradle.properties

Set Kotlin to 2.0.0-RC1

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/synthetic/KSSyntheticAnnotations.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/KspStandaloneDirectInheritorsProvider.kt
kotlin-analysis-api/testData/errorTypes.kt
kotlin-analysis-api/testData/getPackage.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

3 broken tests, two of them are due to changed behaviors in AA and looks right to me.
Have to disable annotation value test due to the new behavior in AA unable to handle local classes as class literals, should be addressed in a follow up fix in upstream.

UPDATE_KOTLIN_VERSION: 2.0.20-dev-2651

---

symbol-processing-aa-embeddable/build.gradle.kts

FQNs starting with `com.intellij` and `org.jetbrains.kotlin` need to be  prefixed by `ksp.`, like what ShadowJar does to classes.

Patch AA service files in renamed uber jar

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/IncrementalKotlinDeclarationProvider.kt

It was a workaround where symbol provider depended on declaration provider. It is no longer needed after KT-66689 was fixed.

Do not index classpath in declaration provider

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/testData/javaModifiers.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JavaModifierProcessor.kt
test-utils/testData/api/javaModifiers.kt

check functional interface for modifiers

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/testData/annotationValue/java.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
test-utils/testData/api/annotationValue_java.kt

Annotation default java

---

common-util/src/main/kotlin/com/google/devtools/ksp/common/IncrementalContextBase.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/GetSealedSubclassesIncIT.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

by just including the files that contain the sealed class / interface.
Their subclasses will be invalidated during dirtiness propagation.

Incremental: fix roots from getSealedSubclasses 

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt

putting it in draft mode since this PR only fixes source symbols. Theoretically it should handle library symbols if psi stub creation for library symbols are in place (as per the document of the psi elements in analysis API symbols). The fix of this PR can be seen by enabling `mangledNames` test, JvmName annotations and internal names should be handled now.
Note that light class still won't handle inline names.

handle internal names and JvmName annotations for name mangling.

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt

Otherwise all annotations are resolved unconditionally when we index KSFiles.

Make originalAnnotations lazy

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/annotationValue/defaultKClassValue.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/DefaultKClassValueProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

map java types to kotlin types when parsing annotation class referece values

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaAsMemberOfProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaGetAllMembersProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaOverridesProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaSupertypesProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPCompilerPluginTest.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/testData/recordJavaAnnotationTypes.kt
kotlin-analysis-api/testData/recordJavaAsMemberOf.kt
kotlin-analysis-api/testData/recordJavaGetAllMembers.kt
kotlin-analysis-api/testData/recordJavaOverrides.kt
kotlin-analysis-api/testData/recordJavaResolutions.kt
kotlin-analysis-api/testData/recordJavaSupertypes.kt
test-utils/testData/api/recordJavaAnnotationTypes.kt
test-utils/testData/api/recordJavaAsMemberOf.kt
test-utils/testData/api/recordJavaGetAllMembers.kt
test-utils/testData/api/recordJavaOverrides.kt
test-utils/testData/api/recordJavaResolutions.kt
test-utils/testData/api/recordJavaSupertypes.kt

Don't merge until 2.0.0-1.0.23 is released.

UPDATE_KOTLIN_VERSION: 2.0.20-Beta2

---

gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
integration-tests/build.gradle.kts

isolatedClassloader only isolates KSP from Gradle classpath. Bundled classes in the KSP jar can still be seen by processors and pollute their classpath. Replacing symbol-processing-aa with
symbol-processing-aa-embeddable solves both issues.
Note that classloaders are still required for:
1. loading KSP2 when needed, so that KSP1 don't download the fat jar.
2. processors need to be re-loaded everytime, in case of improper uses of static variables and/or memory leak.

Use symbol-processing-aa-embeddable in Gradle

---

kotlin-analysis-api/build.gradle.kts

This is similar to https://github.com/google/ksp/pull/1436.

Fix `:kotlin-analysis-api:shadowJar` failing on Windows

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaAsMemberOfProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaGetAllMembersProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaOverridesProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaSupertypesProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPCompilerPluginTest.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/testData/recordJavaAnnotationTypes.kt
kotlin-analysis-api/testData/recordJavaAsMemberOf.kt
kotlin-analysis-api/testData/recordJavaGetAllMembers.kt
kotlin-analysis-api/testData/recordJavaOverrides.kt
kotlin-analysis-api/testData/recordJavaResolutions.kt
kotlin-analysis-api/testData/recordJavaSupertypes.kt
test-utils/testData/api/recordJavaAnnotationTypes.kt
test-utils/testData/api/recordJavaAsMemberOf.kt
test-utils/testData/api/recordJavaGetAllMembers.kt
test-utils/testData/api/recordJavaOverrides.kt
test-utils/testData/api/recordJavaResolutions.kt
test-utils/testData/api/recordJavaSupertypes.kt

Rewind and reapply Kotlin version changes on the 1.0.24-release branch. It won't be necessary from 1.0.25-release on.

UPDATE_KOTLIN_VERSION: 2.0.20-RC

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_kt.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
test-utils/testData/api/annotationValue_java.kt
test-utils/testData/api/annotationValue_kt.kt

The fix is in `kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt`. Other commits are various tests on nested type annotations, based on @kuanyingchou 's test cases.

Nested annotation value: handle non-java-builtin types

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeComparison2Processor.kt
test-utils/testData/api/typeComparison2.kt

Some checks in AA require them to be resolved.
Fixes #1918

Resolve to FirResolvePhase.TYPES for custom types

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

`findProperty` is not compatible with project isolation. The new `providers.gradleProperty` is however.
This partially fixes #1752

Replace usages of findProperty

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

This PR converts all internal things in KspExtension to be properties instead of lists and maps. This will ensure that reads are deferred for as long as possible and will prevent forcing reads during configuration.
Unfortunately some properties cannot be changed without causing changes to the ABI. New properties could be introduced but the names would have to be different.
This partially fixes #1752

Use properties where possible in KspExtension

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/KspSourceModuleBuilder.kt
kotlin-analysis-api/testData/getPackage.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/GetPackageProcessor.kt
test-utils/testData/api/getPackage.kt

in addition to source files in them. This helps AA in computing package scopes.
Fixes #1952

IncrementalGlobalSearchScope: include source roots

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeReferenceResolvedImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ImplicitElementProcessor.kt
test-utils/testData/api/implicitElements.kt

K2 attaches PROPERTY/FIELD unconditionally when deserializing properties/fields in JvmBinaryAnnotationDeserializer.
They cannot be used to determine whether there is a use-site target, or the annotation is immediately on the property/element in the source.
fixes #1882 
ref: https://github.com/JetBrains/kotlin/blob/66ccc6ab3e6cade8a54f874bbed19535528efc96/compiler/fir/java/src/org/jetbrains/kotlin/fir/java/deserialization/JvmBinaryAnnotationDeserializer.kt#L114

Do not use compiler hard-coded use-site target

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/common/PersistentMap.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/BuildCacheIncrementalIT.kt
integration-tests/src/test/resources/buildcache-incremental/build.gradle.kts
integration-tests/src/test/resources/buildcache-incremental/gradle.properties
integration-tests/src/test/resources/buildcache-incremental/settings.gradle.kts
integration-tests/src/test/resources/buildcache-incremental/test-processor/build.gradle.kts
integration-tests/src/test/resources/buildcache-incremental/test-processor/src/main/kotlin/TestBuildCacheProcessor.kt
integration-tests/src/test/resources/buildcache-incremental/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/buildcache-incremental/workload/build.gradle.kts
integration-tests/src/test/resources/buildcache-incremental/workload/src/main/kotlin/p1/K1.kt
integration-tests/src/test/resources/buildcache-incremental/workload/src/main/kotlin/p1/MyAnnotation.kt

Without this change, the task's caches will be in an incorrect state and the next incremental run can lead to compile errors.
Now the caches have been marked as local state and Gradle will remove them when the task is restored from the build cache.
This fixes #2042

Delete the ksp caches when the task is restored from cache

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/MultiplatformIT.kt

kotlinNpmInstall fails too often and has nothing to do with KSP.

Disable MultiplatformIT on Windows

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_kt.kt
kotlin-analysis-api/testData/annotationValue/defaultKClassValue.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt

Use FIR's implementation instead.
Test case is derived from https://github.com/kuanyingchou/ksp/commit/28add760542587b4e1df3a857084afd54259e01f
Fixes #2077

Rollback custom constant value evaluator

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/util/BinaryUtils.kt

so that
1. Cache is queried before reading class file contents.
2. Handles not found classes.
3. Skip on non-jvm platforms.
Fixes #1753 
Fixes #1941 
Fixes #1823

Refactor BinaryUtils.kt

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt

which follows kotlinc.
Fixes #2105

Use `main` when module name of library is unavailable

---

common-deps/src/main/kotlin/com/google/devtools/ksp/KSPConfig.kt
common-deps/src/test/kotlin/com/google/devtools/ksp/CommandLineArgParserTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/cmdline/KSPJvmMain.kt

':' is a valid character in path on Windows.
Fixes #2046

Replace ':' with File.pathSeparator in command line arguments

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/MultipleroundProcessor.kt
test-utils/testData/api/multipleround.kt

This is a temporary workaround for Room. The proper solution is providing `Processor.finish(resolver: Resolver)` and `Processor.onError(resolver: Resolver)` after KSP1 is deprecated.

Don't drop caches before finish/onError

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt

With the change in #2034 a side effect was that KSP2 had to be enabled per Gradle project, not per module.
With this change a DSL property has been added to handle this.

Allow enabling KSP2 per module

---

symbol-processing-aa-embeddable/build.gradle.kts
symbol-processing-cmdline/build.gradle.kts
symbol-processing/build.gradle.kts

so that signing doesn't happen in-place and introduce dangling artifacts.

Copy javadoc and sources in publishing tasks

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/common/IncrementalContextBase.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KotlinInjectIT.kt
integration-tests/src/test/resources/kmp/annotations/src/commonMain/kotlin/com/example/TriggerExceptionAnnotation.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/TriggerExceptionProcessor.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/kmp/workload/src/commonMain/kotlin/com/example/FooBar.kt
integration-tests/src/test/resources/kotlin-inject/build.gradle.kts
integration-tests/src/test/resources/kotlin-inject/settings.gradle.kts
integration-tests/src/test/resources/kotlin-inject/workload/build.gradle.kts
integration-tests/src/test/resources/kotlin-inject/workload/src/commonMain/kotlin/AppComponent.kt
integration-tests/src/test/resources/kotlin-inject/workload/src/commonMain/kotlin/CommonMain.kt
integration-tests/src/test/resources/kotlin-inject/workload/src/jvmMain/kotlin/JvmMain.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/common/IncrementalContextBase.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

Previously, LookupCache doesn't need to be explicitly closed. With newer intellij dependencies that comes with Kotlin 2.0.20 it becomes a problem.
Test cases are contributed by @asapha
Fixes #2072

Close ksp caches on exception and error

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/signatureMapper.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/MapSignatureProcessor.kt
test-utils/testData/api/signatureMapper.kt

by requesting AA to do so implicitly.
Fixes #2109

Expand inline classes before mapping to jvm types

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java2.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
test-utils/testData/api/annotationValue_java.kt
test-utils/testData/api/annotationValue_java2.kt

KSAnnotation.defaultArguments doesn't have arguments without defaults.
Therefore it can be shorter than KSAnnotation.arguments. Their indexes
may not match.
Fixes #2107

Filter default arguments by name, not by index 

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/asMemberOf.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AsMemberOfProcessor.kt
test-utils/testData/api/asMemberOf.kt

for flexible types.
Fixes #2116

asMemberOf: substitude upper and lower bounds recursively

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/KspIntegrationTestRule.kt
gradle.properties
integration-tests/build.gradle.kts
integration-tests/src/test/resources/android-view-binding/app/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/application/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/workload/build.gradle.kts
integration-tests/src/test/resources/playground-android/workload/build.gradle.kts

Previously, the sourceSet-specific KSP configurations (e.g., kspTest) weren't being created when AGP's built-in Kotlin compilation was enabled.
This change also increases the AGP version to 8.7.0-beta01 in order to test against a version of AGP with the built-in Kotlin support.
Bug: b/362279380
Test: GradleCompilationTest

Support AGP's built-in Kotlin compilation

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle.properties

Only K1 and KGP is updated here. KSP2 is awaiting for the fix of [this regression](https://youtrack.jetbrains.com/issue/KT-72002/Analysis-API-psi-KaTypeParameterSymbol-for-default-Java-constructor-is-null) to come in the next Kotlin dev build.

UPDATE_KOTLIN_VERSION: 2.1.0-dev-7621

---

build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/TestProcessor.kt

UPDATE_KOTLIN_VERSION: 2.1.0-Beta2

---

common-util/src/main/kotlin/com/google/devtools/ksp/common/KSObjectCacheManager.kt

Potentially fixes #2073, however unable to test against the [project that reproduced the issue](https://github.com/android/nowinandroid). I checked the other occurrences of ThreadLocal and the one mentioned in KSObjectCacheManager is the only one which seems it needs specific clearing and is clearly a culprit due to various users providing heap dumps across multiple JDK versions.

Fix ThreadLocal memory leaks in KSObjectCacheManager

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/jvmName.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JvmNameProcessor.kt
test-utils/testData/api/jvmName.kt

Handle JvmName in annotation classes

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeAliasImpl.kt
kotlin-analysis-api/testData/javaModifiers.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JavaModifierProcessor.kt
test-utils/testData/api/javaModifiers.kt

KSP2: implement KSTypeAlias.modifiers for libs

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSValueArgumentLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_kt.kt
kotlin-analysis-api/testData/parent.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt

KSP2: Implement KSValueArgument.equals

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeArgumentResolvedImpl.kt
kotlin-analysis-api/testData/typeAlias.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeAliasProcessor.kt
test-utils/testData/api/typeAlias.kt

instead of aliased type. This aligns with KSTypeReference.resolve() which doesn't expand typealiases.
Fixes #2088

KSTypeArgumentResolvedImpl: use aliasing type

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties

This is a pull request to the next, 1.0.27 release branch which is just branched from main. The Kotlin in KSP main branch is newer than the most recent stable release. Therefore, right after branching, we downgrade the Kotlin version to the most recent stable release.
The changes in this PR includes:
1. Kotlin and IntelliJ version changes in `gradle.properties`
2. Corresponding changes due to Kotlin version changes

Downgrade to Kotlin 2.0.21

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml

This reverts commit 2d2e7e7baa01fdb0d0c1915efdbfe319d2e7ad20.
So that it can be cherry-picked from the main branch.

Revert "CI: Update release branch to 1.0.27"

---

build.gradle.kts
common-deps/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestConfig.kt
gradle.properties
integration-tests/build.gradle.kts

Newer AGP is only available with Java 11+ variants. Therefore:
* KSP is compiled with older AGP and targeting Java 8.
* Gradle tests and integration tests run with newer AGP.

Set JVM target back to Java 8.

---

build.gradle.kts
common-deps/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestConfig.kt
gradle.properties
integration-tests/build.gradle.kts

Newer AGP is only available with Java 11 variants. Therefore:
* KSP is compiled with older AGP and targeting Java 8.
* Gradle tests and integration tests run with newer AGP.
(cherry picked from commit 579c9daf5227d736520b9bbd07dd5de962e9f138)

cherry-pick to 1.0.27: Set JVM target back to Java 8.

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

* Dirtiness didn't propagate across generated files previously.
* Also fixes the issue of using out-of-date PSIs when getting paths.

KSP2: update for all, not just initial dirty sources

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/getSymbolsFromAnnotationInLib.kt

for aliased annotations in libraries.
Fixes #2024

KSP2: Reimplement getSymbolsWithAnnotation

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/KspIntegrationTestRule.kt

Previously, when the KSP plugin was applied before AGP and AGP's built-in Kotlin support for test fixtures or screenshot tests was enabled, there would be an error when building.
The underlying cause for this error is
https://github.com/gradle/gradle/issues/31092, which caused the KSP plugin to try to access the android extension before AGP's apply method had completed.
This change fixes the problem by using the "com.android.base" plugin as the indicator that a module is an Android module. The "com.android.base" plugin is applied after the android extension has been added, so it works around the Gradle bug.
Bug: https://github.com/google/ksp/issues/2174
Test: GradleCompilationTest

Fix error when KSP plugin applied before AGP

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
kotlin-analysis-api/testData/jvmName.kt
test-utils/testData/api/jvmName.kt

Fix JVM names for properties starting with 'is'

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

If the corresponding Kotlin native compilation is disabled, KSP should be disabled as well.
This aligns with KSP1's behavior.
Fixes #2173

Disable KSP2 tasks with corresponding compilation

---

docs/ksp2cmdline.md
docs/ksp2entrypoints.md
integration-tests/build.gradle.kts

This is a followup of unbundling kotlinx.coroutines, which needs to be explicitly included in the classpath.

Fix a dependency of integration-tests

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIT.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/playground/workload/src/main/java/com/example/AClass.kt

by mimicking the rules from KGP.
fixes #2180

KSP2: fix module names for Android builds

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt

so that each KSP task can configured differently.

Introduce KspAATask.commandLineArgumentProviders

---

kotlin-analysis-api/src/main/java/com/intellij/util/concurrency/AppScheduledExecutorService.java
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/cmdline/KSPJvmMain.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

1. Call exitProcess in command line tools.
2. Set application pool threads to daemon.
Fixes #2176

Workarounds for blocking threads in IntelliJ libs

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

which was an lefe-over when moving to IncrementalGlobalSearchScope.
It also causes a problem when users wire generated outputs to source sets.
Prevents #2230

KSP2: clean up legacy incremental code

---

.github/workflows/auto-merge.yml

for accidentally created merge commits.

CI: Update DONT_PICK

---

kotlin-analysis-api/src/main/kotlin/com/intellij/util/lang/JavaVersion.java

from upstream Kotlin repo. See KT-73967 for details.
https://youtrack.jetbrains.com/issue/KT-73967
Verified by examining the artifacts locally.

Copy com.intellij.util.lang.JavaVersion

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/checkOverride.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/CheckOverrideProcessor.kt
test-utils/testData/api/checkOverride.kt

override cannot happen without visibility.
fixes #2254

Add visibility check in ResolverAAImpl.overrides

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/EqualsProcessor.kt
test-utils/testData/api/equals.kt

This works around an issue that equals not working for KaFirNamedClassSymbol and KaFirPsiJavaClassSymbol. See KT-74598 for details.
Fixes #2246

Try to find KaFirPsiJavaClassSymbol if possible

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassifierReferenceDescriptorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/equivalentJavaWildcards.kt
kotlin-analysis-api/testData/javaWildcards2.kt
test-utils/testData/api/equivalentJavaWildcards.kt

1. number of type parameters and type arguments mismatch. #2265 
2. Some `out` variances are incorrectly optimized away. #2264 
3. Star-projected invariant parameter should become covariant.
and also
4. Fixed type expansion; previously some type parameters were not substituted.
5. KSP1: KSTypeArgument.parent should be KSClassifierReference, instead of KSTypeReference.
finally,
6. Enabled the remaining tests around Resolver.getJavaWildcard.

Fix various issues around Resolver.getJavaWildcard

---

compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSAnnotationImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties

The latest 3 Kotlin version changes for 2.1.10 are reverted, and then a new commit bumps Kotlin from 2.1.20-Beta1 to 2.1.20-Beta2.

Rewind Kotlin version changes and bump to 2.1.20-Beta2

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
.github/workflows/release.yml

v3 was deprecated and starts to fail CI.

CI: bump actions/upload-artifact to v4

---

gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestConfig.kt
gradle.properties
gradle/wrapper/gradle-wrapper.properties
integration-tests/build.gradle.kts
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AGP741IT.kt

Use AGP's new addKspConfigurations() API when possible.
Bug: https://github.com/google/ksp/issues/2250
Test: AGP741IT and existing ProcessorClasspathConfigurationsTest

Partially migrate KSP off AGP's legacy Variant API

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIT.kt

The issue mentioned in(https://github.com/google/ksp/issues/299#issuecomment-898207658) has been resolved in recent AGP

Enable configuration cache for AndroidIT

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationNestedClassValueProcessor.kt
test-utils/testData/api/annotationWithNestedClassValue.kt

```
object Root {
class Nested
}
annotation class MyAnnotation(val clazz: KClass<*>)
@MyAnnotation(Root.Nested::class)
fun main() = Unit
```
`getAnnotationsByType(MyAnnotation::class).first().clazz`
`Map.Entry.class.getName()` prints `java.util.Map$Entry`
`Map.Entry.class.getCanonicalName()` prints `java.util.Map.Entry`
ksp's `qualifiedName` for `Map.Entry` is `java.util.Map.Entry`
ksp's `qualifiedName` is equivalent to Java's `Class.getCanonicalName` but `Class.forName` requires fully qualified name (`Class.getName`).

fix `KSTypeNotPresentException` for an existing nesting class

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionImpl.kt
kotlin-analysis-api/testData/typeAlias.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeAliasProcessor.kt
test-utils/testData/api/typeAlias.kt

AA expands types by default. Luckily, the abbreviations are handily available. This change makes KSFunction behave the same as other parts that return KSType in the API.

KSFunction: return type aliases if possible

---

compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSAnnotationImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties

This patch is generated by `git diff origin/main origin/1.0.30-release`.

Downgrade to Kotlin 2.1.10 on 1.0.31-release

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

This PR is a quick proposal to address issue #2340.  
The current implementation tracks `java.home` as an input, causing cache misses when the value differs. This not only affects CI vs. local builds but also causes issues in local environments if the user updates the minor or patch versions of Java, as the input value changes.  
This PR updates the JDK home input to be marked as `@Internal` and introduces a new input, `jdkVersion`, to track the major Java version.  
The implementation follows the current style by retrieving the system property `java.version`. The purpose of using `jdkVersion` is to ensure that the task is invalidated if the major Java version changes, similar to how Java handles compatibility with the Java compiler.  
I am not entirely convinced by this approach because …

jdkHome as internal and creating new jdkVersion input

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalCPIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalEmptyCPIT.kt

Previously, KSP directly used the classpath/library to detect incremental changes and prevents compilation avoidance. Now, it uses classpathStructure which takes compilation avoidance and specialties of annotation processing into account.

Better support of Gradle compilation avoidance

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/IsMutableProcessor.kt
test-utils/testData/api/isMutable.kt

A commit in 1.0.30 caused the implementation of this specific Java field to become KSPropertyDeclarationJavaImpl, and thus surfaced this bug.

KSP2: Fix KSPropertyDeclaration.isMutable for Java libs

---

compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSAnnotationImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties

patch generated by `git diff origin/main origin/1.0.31-release | patch -p1`

1.0.32-release: downgrade to Kotlin 2.1.10

---

compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSAnnotationImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties

do not merge before the release of 2.1.10-1.0.31.

1.0.31-release: bump to Kotlin 2.1.20-RC

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt

1. KSFileJavaImpl: compuate packageName and location lazily
2. Simplify KSTypeImpl.getCached

More optimizations for KSNode creation

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationTargetsProcessor.kt
test-utils/testData/api/annotationTargets.kt

Annotations on properties may come from corresponding parameters if they are declared in constructors. They may not be valid on properties and need to be filtered out. The previous implementation incorrectly excludes all annotations with @Target(AnnotationTarget.VALUE_PARAMETER), while what should be excluded are the ones with @Target and without @Target(AnnotationTarget.PROPERTY).

Fix validity check of annotations on properties

---

common-util/src/main/kotlin/com/google/devtools/ksp/common/visitor/CollectAnnotatedSymbolsVisitor.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/locations.kt

Previous implementation needs to scan through all symbols with annotations each time getSymbolsWithAnnotation is called. Let's just store the symbols in a map and index by annotations.

Store collected symbols by annotations

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/common/PsiUtils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeArgumentResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeReferenceResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt

where the intermediate functions applied on the sequence are pure and cost effective.
Unlike simple lazy values, intermediate functions applied in lazy properties of Sequence types are computed repeatedly. For example, square() is called each time x is read.
val x: Sequence<Int> by lazy { listOf(1, 2, 3).map { square(it) } }
lazyMemoizedSequence caches the values of the sequence.
Also replaced the stateful implementation of
KSClassDeclarationImpl.declarations by a stateless one.

Replace lazy Sequences by lazyMemoizedSequence

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
.github/workflows/release.yml
buildSrc/src/main/kotlin/com/google/devtools/ksp/ApiCheck.kt
integration-tests/build.gradle.kts

and update CI to use check instead of test.
This is a replacement of the attempt in #2178, which actually runs integration tests twice.
ktlint is removed from main.yml as it is included by `check` already.
Also fixed a case in ApiCheck where libraries can be out of project root.

Decouple AGP tests with other integration tests

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/processor/ValueParameterProcessor.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/valueParameter.kt

for symbols from libraries.
Fixes #1192 and #2348

KSP2: fix KSValueParameter.isVal and isVar

---

docs/ksp2api.md
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/equivalentJavaWildcards.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/VarargProcessor.kt
test-utils/testData/api/vararg.kt

Previously, KSValueParameter.type was an array when it is from Kotlin sources, while it is the declared type for Java and libraries.
For example, the KSValueParameter.type of strings is now consistently String.
fun (vararg strings: String)
The equivalentJavaWildcards test is updated due to a toString() change.

KSP2: fix the type of vararg for Kotlin sources

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/IncrementalKotlinPackageProviderFactory.kt

It has to be done manually because it is wrapped by IncrementalPackageProviderFactory.
Tested with Room's test suite where the issue was discovered. Also verified with debugger that KotlinCachingPackageProviderFactory is no longer sticky.

Register KotlinStandalonePackageProviderFactory to project Disposable

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeReferenceResolvedImpl.kt

instead of the underlying type, which can be confusing and inconsistent to other implementations of KSTypeReference.

KSTypeReferenceResolvedImpl.toString(): render unexpanded

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

1. Exclude KAPT generated classes from class path snapshots. This fixes #1280. Tested locally with a sample project from @luboganev. Not sure why this bug is not caught by `KAPT3IT` yet and still investigating.
2. Enable class path snapshots based incremental processing on Android builds, which was accidentally omitted previously. Hopefully this will make Android builds much faster.

A couple of fixes to compilation avoidance

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/BinaryGenProcessor.kt

Currently,
1. It only works on JVM.
2. Generated classes are not available within processing rounds.

KSP2: Support generated binary classes

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/symbol/AnnotationUseSiteTarget.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/testData/annotationInDependencies.kt
test-utils/testData/api/nestedAnnotations.kt

for the new `all` annotation use site target.
https://github.com/Kotlin/KEEP/blob/master/proposals/annotation-target-in-properties.md
Also fixed a couple of tests where `setparam` should only be propagated
to synthetic setter paramaters.
TODO: configure `-Xannotation-defaulting` / `LanguageFeature.PropertyParamAnnotationDefaultTargetMode` according to the corresponding compilation.

Introduce AnnotationUseSiteTarget.ALL

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt

and unconditionally register KSP tasks.
configurationsForMultiplatformApp_doesNotCrossCompilationBoundaries is
removed because the use case of declaring multiple similar targets is no
longer supported in Kotlin 2.2.
Fixes #1789

Do not resolve configuration in configuration time

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt

The old scheme was deprecated since 1.4.30.
Fixes #1493

KSP1: use new mangling scheme for inline classes

---

gradle.properties

Cherry-pick "Switch to Lint with K2 UAST" to 2.0.2-release manually

---

api/build.gradle.kts
common-deps/build.gradle.kts
common-util/build.gradle.kts
compiler-plugin/build.gradle.kts
gradle-plugin/build.gradle.kts
kotlin-analysis-api/build.gradle.kts
symbol-processing-aa-embeddable/build.gradle.kts
symbol-processing-cmdline/build.gradle.kts
symbol-processing/build.gradle.kts
test-utils/build.gradle.kts

It reduces eagerly created tasks from 21 to 8
It also removes usages of deprecated tasks.create APIs
Before:
https://scans.gradle.com/s/c7nuxleridqpa/performance/configuration#summary-task-created-immediately
After:
https://scans.gradle.com/s/ujjfmvljy65xo/performance/configuration#summary-task-created-immediately

Clean up task registering in kts build scripts

---

build.gradle.kts

Disables timestamps and enables reproducable order for KSP jars
Test: ./gradlew publishToMavenLocal -> inspect jars

Make built jars reproducible

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeReferenceResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java2.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_kt.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt

Origin of arguments of synthetic / default anntations should be where they were mentioned.
TODO: unify the the implementations by getting rid of Kotlin psi and Java psi.

Fix origin of arguments of synthetic annotations

---

.gitignore
common-deps/src/main/kotlin/com/google/devtools/ksp/KSPConfig.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/InternalOfFriendsProcessor.kt
test-utils/testData/api/internalOfFriends.kt

`KSPConfig.friends` is introduced and used to configure friend modules. It is similar to `KSPConfig.libraries`, the main difference is that their `internal` elements are visible to current module.
The flag in KGP isn't available yet so the Gradle part is in the ToDo list.

Support friend modules

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

It was removed in the main branch in
2399ccd00f8dbc2d51cf223160c459b23e806f07 and blocking the auto-merger. It's not used anymore even in 2.0.2-release so let's remove it.

Remove classpathSnapshotProperties.classpath

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

Some profilers resolve names too late and the resolution may fail because the classloaders and processors are already garbage collected. This mode simply keeps references to processor classloaders. Therefore, it is disabled by default and should only be used when profiling.

New gradle property: `ksp.ksp2.profiling.mode`

---

README.md
build.gradle.kts

OSSRH was deprecated on 2025.6.30.
(cherry picked from commit bf0e0f7aefa753d639f52a163d777a767d0c28fd)

cherry-pick: Publishing: Switch to Central Portal

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

This PR addresses [google/ksp#2467](https://github.com/google/ksp/issues/2467).
The issue originates from the `MapProperty` `processorOptions` in `KspGradleConfig` when using `KspAATask`. This map is populated with command-line argument values, but it is not aware of Gradle’s path sensitivity requirements, which leads to incorrect behavior, causing remote cache misses.
As a workaround, this PR marks `processorOptions` as `@Internal` and instead relies on `commandLineArgumentProviders` in `KspAATask` to correctly track these inputs. To support this, similar to what is done in `KspJvmTask`, we inject the KSP extension's command-line argument providers into the task command line argument.
Since `processorOptions` is also populated from kspExtension.apOptions, we introduce a new MapProperty …

Marking processorOptions as internal (KspAATask)

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

There are 2 commits in this PR:
1. Most of the changes come from [Revert "Downgrade to Kotlin 2.1.21"](https://github.com/google/ksp/commit/73947b2f22563ad56216134483c304f20f81c610).
2. The second commit is a single line change in the `gradle.properties` that changed the Kotlin version for KSP1 and KSP Gradle Plugin to 2.2.0.

2.0.3-release: Bump to Kotlin 2.2.0

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Instead of using Variant object, we should store the Components as they match closely with the Kotlin Compilations which is passed to each applyToCompilation() invocation.

Changes to the android cache

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

This fixes a weird bug we are seeing in the Apollo Kotlin repository. 
More specifically, this branch: https://github.com/apollographql/apollo-kotlin/tree/reproducer-ksp
Our KSP processor fails to find annotation in dependencies:
```
$ ./gradlew :apollo-debug-server:kspCommonMainKotlinMetadata
> Task :apollo-debug-server:kspCommonMainKotlinMetadata FAILED
e: [ksp] No '@GraphQLQuery' class found
```
After invastigating it, this seems to be because no libraries are passed to the KSP task.
More specifically, the sequence of operation is this:
* `compilation.compileDependencyFiles` is set [here](https://github.com/Jetbrains/kotlin/blob/56b84a68ab6c20ff99734bec499ad53d3cecaf2e/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/targets/metadata/KotlinMetadataTarge …

Evaluate `compilation.compileDependencyFiles` lazily

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
integration-tests/build.gradle.kts
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AGP810IT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AGP812IT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AGP890IT.kt

That API had a critical fix in 8.12.0-alpha06
Below that version we can't use that API

Call addGeneratedSourceDirectories behind AGP version runtime check

---

docs/ksp2cmdline.md

Hello,
We are currently building support for [KSP 2 in mill](https://github.com/com-lihaoyi/mill/pull/5727) and after some trial and error, we were successful in building dagger/hilt and micronaut apps.
Since we've done the investigation, I thought you might be interested in freshening up the docs. This PR updates the versions to the latest kotlin and ksp and adds some notable mentions which took me some time to figure out and I believe it would be easier if these were mentioned (especially the `-libraries` is the argument I missed and spent a few ours looking around to figure out how classpaths are passed in).
Please let me know what you think and if this update is useful to you, otherwise feel free to close the pull request.
Kind regards

Freshen up docs for latest ksp/kotlin versions

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/util/BinaryUtils.kt
kotlin-analysis-api/testData/libOrigins.kt

The hack was erroneous and no longer needed.
Also added sanity checks before calling asm's ClassReader, which doesn't expect invalid class formats.
Fixes #2548

Clean mapAAOrigin up
