google/ksp

README.md
old-ksp-release.md

Also update to ksp-1.4.10-dev-experimental-20200924.

Add an example of migrating from old releases.

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ImplicitElementProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/allFunctions.kt
compiler-plugin/testData/api/implicitElements.kt

* Add support for default constructor of Java class.
* Fixed getDeclaredFunctions which will return duplicate elements for
all constructors.

Fix Java class constructor calculation.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

So that they are under the same, sourceSetName based destinationDir.
Fixes #157

Reorganize output directories.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/DeclarationInconsistencyProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/declarationInconsistency.kt

See https://github.com/google/ksp/issues/195 for details.

Replace `mockSerializableType` with real one.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaAsMemberOfProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaGetAllMembersProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaOverridesProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaSupertypesProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSAnnotationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
compiler-plugin/testData/api/recordJavaAnnotationTypes.kt
compiler-plugin/testData/api/recordJavaAsMemberOf.kt
compiler-plugin/testData/api/recordJavaGetAllMembers.kt
compiler-plugin/testData/api/recordJavaOverrides.kt
compiler-plugin/testData/api/recordJavaResolutions.kt
compiler-plugin/testData/api/recordJavaSupertypes.kt

This is WIP but mostly done; The only remaining task is running integration tests.

Insert simulated lookups for Java sources

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

The compilation task doesn't take care of them.

Remove resources from Kotlin sources

---

.github/workflows/main.yml
api/build.gradle.kts
build.gradle.kts
gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/processor/TestSymbolProcessor.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/DependencyDeclaration.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/KspIntegrationTestRule.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/PluginDeclaration.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestConfig.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestModule.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/testing/TestProject.kt
gradle.properties
gradle/wrapper/gradle-wrapper.properties
integration-tests/build.gradle.kts
symbol-processing/build.gradle.kts

This PR adds a testing infra for the gradle plugin and also
adds support for android variants.

Add integration tests for plugin

---

README.md
docs/quickstart.md

1. Library support table
2. Update README to include latest speedup stats (up to 2x)
3. Fix broken playground link in quickstart

Add library support table and other doc updates

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt

Resolver.getAllFiles() should include newly generated files.

Fix Resolver.getAllFiles() in multiple round

---

README.md
api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/CodeGeneratorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/MessageCollectorBasedKSPLogger.kt

Also includes a minor commit for README update.

Error handling for SymbolProcessor.

---

docs/quickstart.md

Fixing the order of repository definitions and remove NBSP in QuickStart.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt

AGP "com.android.base" plugin is applied before the AGP extension
is created, so it is too early to access it. This change waits for
application, library, or dynamic-feature plugins to be applied before
decorating the extension.
Fixes #314

AGP callback only once app/lib/dynamic-feature plugin is applied

---

docs/quickstart.md

Update quickstart.md with block explaining how to setup using groovy
Add collapsible blocks with explanation on how to setup the ksp plugin in a project that uses groovy

Add doc how to setup with groovy

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalIT.kt
integration-tests/src/test/resources/incremental/workload/src/main/kotlin/p1/K1.kt
integration-tests/src/test/resources/incremental/workload/src/main/kotlin/p1/K2.kt

Fix delimiter used to pass changed files

---

integration-tests/src/test/resources/playground-android/gradle.properties

It's contents are generated in test.

Delete unnecessary / confusing gradle.properties in test

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
api/src/main/kotlin/com/google/devtools/ksp/utils.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/ThrowListProcessor.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/testData/api/throwList.kt

* Add function to Resolver for getting checked exception from Java method
* Add a utility function for getting throw list from Kotlin function as declared in `@Throws` annotation

Support throw list

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyAccessorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertySetterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSValueParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSValueParameterSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/testData/api/annotationInDependencies.kt

Actually logic is becoming more complicated to the degree I am thinking of delegate to descriptors directly, but posting this solution for avoiding resolution anyway. I'm open to switch to descriptor based solution on this.

support annotation use site target of @setparam

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/VersionCheckIT.kt

by setting `ksp.version.check=false`.

Allow version mismatch warning to be muted

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Label properties explicitly for Gradle

---

README.md

Room now has experimental support.

Update library support table

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/GeneratedRefsIncIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/GeneratedSrcsIncIT.kt
integration-tests/src/test/resources/refs-gen/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/refs-gen/workload/src/main/kotlin/com/example/Bar.kt
integration-tests/src/test/resources/refs-gen/workload/src/main/kotlin/com/example/Baz.kt
integration-tests/src/test/resources/srcs-gen/test-processor/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/srcs-gen/workload/src/main/kotlin/com/example/Bar.kt
integration-tests/src/test/resources/srcs-gen/workload/src/main/kotlin/com/example/Baz.kt
integration-tests/src/test/resources/test-processor/build.gradle.kts
integration-tests/src/test/resources/test-processor/settings.gradle.kts
integration-tests/src/test/resources/test-processor/test-processor/build.gradle.kts
integration-tests/src/test/resources/test-processor/test-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessor
integration-tests/src/test/resources/test-processor/workload/build.gradle.kts

Register generated sources in incremental caches

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt

The `ArrayIndexOutOfBoundsException` in #388 seems to be a result of unclosed files in previous builds in `KotlinCompileDaemon`, even when they are not touched. There are also other random IO related exceptions. All of them disappeared after this commit. Running *in-process* also make the issue away.

IncrementalContext: close files on exception

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalIT.kt

Previously, it's done by adding to ksp tasks' source, which incorrectly
made Gradle think it is part of the source as a side-effect.

Add processor into ksp tasks' inputs

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

I thought this was force pushed in #394 , but apparently not.

Synthesize an unique name for processor classpath

---

docs/incremental.md

Missing space between text and link.

Add missing space in docs

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processor/DeclarationPackageNameProcessor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFileJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFileImpl.kt
compiler-plugin/testData/api/declarationPackageName.kt

Make default package name an empty string

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/testData/api/getSymbolsFromAnnotation.kt

support value parameter for getSymbolsWithAnnotation

---

api/src/main/kotlin/com/google/devtools/ksp/symbol/KSFunctionDeclaration.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSFunctionDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/OverrideeProcessor.kt
compiler-plugin/testData/api/overridee.kt

fix findOverridee for kotlin/java properties.

---

api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessorProvider.kt

Make SymbolProcessorProvider a fun interface

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt

It was registered using a TestOnly API previously.

Register PsiTreeChangeListener properly

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
api/src/main/kotlin/com/google/devtools/ksp/visitor/KSValidateVisitor.kt
compiler-plugin/testData/api/validateTypes.kt

While this does not fundamentally fix #368 , default validate still should not consider  function body for performance.

default symbol validation should not check function body

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIT.kt
integration-tests/src/test/resources/playground-android/workload/build.gradle.kts
integration-tests/src/test/resources/playground-android/workload/proguard-rules.pro
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/BuilderProcessor.kt

Register resources to variant postJavacGeneratedBytecode

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
compiler-plugin/testData/api/annotationValue.kt

fix findDeclaration() for Java Enum entry value

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ThrowListProcessor.kt
compiler-plugin/testData/api/throwList.kt

add Resolver.getJvmCheckedException for property accessors

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/DualLookupTracker.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKotlinKSPTest.kt
docs/incremental.md
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalCPIT.kt
integration-tests/src/test/resources/incremental-classpath/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/gradle.properties
integration-tests/src/test/resources/incremental-classpath/l1/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/l1/src/main/kotlin/p1/L1.kt
integration-tests/src/test/resources/incremental-classpath/l2/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/l2/src/main/kotlin/p1/L2.kt
integration-tests/src/test/resources/incremental-classpath/l3/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/l3/src/main/kotlin/p1/L3.kt
integration-tests/src/test/resources/incremental-classpath/settings.gradle.kts
integration-tests/src/test/resources/incremental-classpath/validator/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/validator/src/main/kotlin/Validator.kt
integration-tests/src/test/resources/incremental-classpath/validator/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/incremental-classpath/workload/build.gradle.kts
integration-tests/src/test/resources/incremental-classpath/workload/src/main/kotlin/p1/K1.kt
integration-tests/src/test/resources/incremental-classpath/workload/src/main/kotlin/p1/K2.kt
integration-tests/src/test/resources/incremental-classpath/workload/src/main/kotlin/p1/K3.kt

A conflict needs to be resolved manually.

Cherry pick PR 525 into kotlin-1.5.21

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ThrowListProcessor.kt
compiler-plugin/testData/api/throwList.kt

support checked exceptions declared in class files

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

and fix a few annotations on properties of KspTask.

Support Gradle build cache

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/MangledNamesProcessor.kt
compiler-plugin/testData/api/mangledNames.kt

check name instead of psi for PSI synthetic elements

---

docs/quickstart.md

It's good for newcomers to know of this workaround while https://github.com/google/ksp/issues/37 is open.

Update Quickstart instructions on IDE mapping of generated files

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/MultiplatformIT.kt
integration-tests/src/test/resources/kmp/workload/build.gradle.kts

Native: skip targets if unsupported on host

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt

update logger key to use the unwrapped logger from compiler

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/TypeParameterReferenceProcessor.kt
compiler-plugin/testData/api/typeParameterReference.kt

construct correct JavaResolverContext for java type resolver

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalCPIT.kt

Also label isKspIncremental and isIntermoduleIncremental with @Input

Disable isIntermoduleIncremental when isIncremental is false

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/testData/api/annotationValue.kt
integration-tests/src/test/resources/kmp/gradle.properties

handle annotation argument of type kotlin array reflection object

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIncrementalIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/fixtures/BuildResultFixture.kt
integration-tests/src/test/resources/playground-android-multi/application/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/application/src/main/AndroidManifest.xml
integration-tests/src/test/resources/playground-android-multi/application/src/main/java/com/example/application/Foo.kt
integration-tests/src/test/resources/playground-android-multi/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/gradle.properties
integration-tests/src/test/resources/playground-android-multi/settings.gradle.kts
integration-tests/src/test/resources/playground-android-multi/test-processor/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/workload/build.gradle.kts
integration-tests/src/test/resources/playground-android-multi/workload/src/main/AndroidManifest.xml

... in order to test incremental Kotlin compilation
if KSP is applied in the library, to address issue #647.
Test: AndroidIncrementalIT

Add test project with Android library and application

---

build.gradle.kts
gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/VersionCheckIT.kt

so as to make recommendation to Kotlin versions.

Write versions to sources

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ThrowListProcessor.kt
compiler-plugin/testData/api/throwList.kt

fix checked exception retrieving logic for compiled java constructor

---

README.md

Update Lyricist library status from experimental to officially supported.

chore: update lyricist support status

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/testData/api/declarationUtil.kt
compiler-plugin/testData/api/getSymbolsFromAnnotation.kt
compiler-plugin/testData/api/overridee.kt

fix ordering for properties declared inside constructors

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/VersionCheckIT.kt

which use more memory and seem to cause OOM in CI.

Remove unnecessary debug flags

---

README.md

As of 2.7.0 Kotshi has official KSP support

Update Kotshi in the readme

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSTypeReferenceSyntheticImpl.kt
compiler-plugin/src/test/java/com/google/devtools/ksp/test/KotlinKSPTestGenerated.java
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/EquivalentJavaWildcardProcessor.kt
compiler-plugin/testData/api/equivalentJavaWildcards.kt

which computes the corresponding Java wildcard, from the given
reference.

Introduce Resolver.getJavaWildcard

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/resources/kmp/annotations/build.gradle.kts
integration-tests/src/test/resources/kmp/annotations/src/commonMain/kotlin/com/example/MyAnnotation.kt
integration-tests/src/test/resources/kmp/settings.gradle.kts
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/ValidateProcessor.kt
integration-tests/src/test/resources/kmp/workload-androidNative/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-androidNative/src/commonMain/kotlin/com/example/ToBeValidated.kt
integration-tests/src/test/resources/kmp/workload-js/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-js/src/commonMain/kotlin/com/example/ToBeValidated.kt
integration-tests/src/test/resources/kmp/workload-jvm/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-jvm/src/commonMain/kotlin/com/example/ToBeValidated.kt
integration-tests/src/test/resources/kmp/workload-linuxX64/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-linuxX64/src/commonMain/kotlin/com/example/ToBeValidated.kt
integration-tests/src/test/resources/kmp/workload-linuxX64/src/linuxX64Test/kotlin/MyTest.kt
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/src/commonMain/kotlin/com/example/ToBeValidated.kt
integration-tests/src/test/resources/kmp/workload/src/linuxX64Test/kotlin/MyTest.kt

Also updated test cases for all platforms.
TODO: K/N

Correct compiler args for JSIR tasks

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ParentProcessor.kt
compiler-plugin/testData/api/parent.kt

Unfortunately, LightMethod doesn't implement parent and need a special
treatment.

Find parents for LightMethod

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/VisibilityProcessor.kt
compiler-plugin/testData/api/visibilities.kt

enum class constructor should have private visibility

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/testData/api/getSymbolsFromAnnotation.kt

Handle import aliases for getSymbolsWithAnnotation

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/testData/api/annotationWithDefault.kt

handle enum entry evaluation for annotation default value

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalMultiChainIT.kt
integration-tests/src/test/resources/incremental-multi-chain/build.gradle.kts
integration-tests/src/test/resources/incremental-multi-chain/gradle.properties
integration-tests/src/test/resources/incremental-multi-chain/processors/build.gradle.kts
integration-tests/src/test/resources/incremental-multi-chain/processors/src/main/kotlin/Aggregator.kt
integration-tests/src/test/resources/incremental-multi-chain/processors/src/main/kotlin/ImplGen.kt
integration-tests/src/test/resources/incremental-multi-chain/processors/src/main/kotlin/Validator.kt
integration-tests/src/test/resources/incremental-multi-chain/processors/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/incremental-multi-chain/settings.gradle.kts
integration-tests/src/test/resources/incremental-multi-chain/workload/build.gradle.kts
integration-tests/src/test/resources/incremental-multi-chain/workload/src/main/kotlin/K1.kt
integration-tests/src/test/resources/incremental-multi-chain/workload/src/main/kotlin/Main.kt

by input-output relations and lookup dependencies.
Fixes #814

Combine dirtiness propagation

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/CheckOverrideProcessor.kt
compiler-plugin/testData/api/checkOverride.kt

this function checks if a declaration is overriding another declaration in the context of contained in the containing class.

Add Resolver.overrides(overrider: KSDeclaration, overridee: KSDeclaration, containingClass: KSClassDeclaration): Boolean

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/ReplaceWithErrorTypeArgsProcessor.kt
compiler-plugin/testData/api/replaceWithErrorTypeArgs.kt

Allow empty list to asType

---

README.md

[EasyAdapter](https://github.com/AmrDeveloper/EasyAdapter) is a Library to generate your adapters only with Annotations on your model using KSP
Thanks for KSP ❤️

Add EasyAdapter to supported libraries

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
api/api.base
api/build.gradle.kts
buildSrc/src/main/kotlin/com/google/devtools/ksp/ApiCheck.kt

Track API changes in CI

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Also fixed source filtering; Configuration cache doesn't like it being
done at configuration time.
The source filtering and configuration cache issue is discovered by the updated test case.

Add KotlinCompile task dependencies to KSP tasks

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/TestProcessor.kt

fix super types for non-jvm target

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml

1.0.6-release was just created.
Please don't merge this PR yet before 1.0.5-release is out, in case there is anything to fix.

Update CI for 1.0.6-release branch

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

* Run tests on auto-merge for Linux and Mac.
* Run daily tests for all branches on Windows.
* Test for Windows in release action.
Creating this new PR so I can test auto-merge on my own repository.

Update github actions.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/testData/api/annotationWithDefault.kt

preprocess file classes into binding trace

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
compiler-plugin/testData/api/sealedClass.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/SealedClassProcessor.kt

(cherry picked from commit 089f0f752d19f87be742a1d061e7ef79e91beaaa)
to fix auto-merge conflict on 1.0.6 release branch.

try to get psi before creating sealed sub class declarations

---

kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt

* replace analyseWithSymbolAsContext with analyze(ktModule)

AA: advances analysis API version to 1.7.20-dev-1353

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSFunctionDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSFunctionDeclarationImpl.kt
compiler-plugin/testData/api/overridee.kt
compiler-plugin/testData/api/signatureMapper.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/MapSignatureProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/OverrideeProcessor.kt

fixes #1004 
Currently this issue seems to only happen for annotations declared in Java source.

fix annotation value resolution for annotations declared in Java source.

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSErrorType.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSErrorTypeClassDeclaration.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSExpectActualImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFileJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeAliasImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

also includes an implementation for KSTypeAlias, as well as some refactoring for common logics for KSDeclaration.

AA: Implement KSErrorType

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt

Unfortunately, test is still blocked by multiple test causing duplicate extension registration issue

AA: add type creation API

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle.properties

(cherry picked from commit 5767b1f9fc7c2854239ff6efa79692979524aec4)

UPDATE_KOTLIN_VERSION: 1.7.20-Beta

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
compiler-plugin/testData/api/annotationOnConstructorParameter.kt
compiler-plugin/testData/api/annotationValue_java.kt
compiler-plugin/testData/api/annotationValue_kt.kt
compiler-plugin/testData/api/hello.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/HelloProcessor.kt

* implemented reading annotation arguments declared in Kt source.
* implemented annotation default value reading for Kt sources.
* implemented function local declarations.
* refactored `KSType.declaration` for better handling local classes.
* refactored `KSClassDeclaration` implementation to use more abstract KtSymbol.
* split annotationValue tests into kotlin and java.
* unmutes annotationValue_kt test.

AA: implement annotation argument value

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeComposureProcessor.kt

unmutes 2 tests along the way.

AA: abstraction for converting KSTypeArgument to KtTypeArgument

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/DualLookupTracker.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
gradle.properties

* implement LookupTracker.clear()
* filter `entries` out in enums

UPDATE_KOTLIN_VERSION: 1.8.0-dev-2355

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/build.gradle.kts
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KSPCmdLineOptionsIT.kt
integration-tests/src/test/resources/cmd-options/build.gradle.kts
integration-tests/src/test/resources/cmd-options/processors/build.gradle.kts
integration-tests/src/test/resources/cmd-options/processors/src/main/kotlin/TestProcessor.kt
integration-tests/src/test/resources/cmd-options/processors/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/cmd-options/settings.gradle.kts
integration-tests/src/test/resources/cmd-options/workload/build.gradle.kts
integration-tests/src/test/resources/cmd-options/workload/src/main/kotlin/com/example/A.kt

respect returnOkOnError when withCompilation is set true.
fixes #974

fix behavior for KSP error case with compilation.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
integration-tests/src/test/resources/kmp/test-processor/src/main/kotlin/ValidateProcessor.kt

The fix in the compiler won't be available before 1.8.20.
The workaround comes from https://github.com/google/ksp/pull/1049

Apply the nested java class workaround more

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSClassDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationLocalVariableImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/testutils/AbstractKSPTest.kt

also fixes multiple module test
unmutes declarationPackageName test.

AA: support local variables as KSPropertyDeclaration.

---

gradle.properties

This reverts commit 474d8528684f511df62e1b492c4a1e5cee307ac6.

Revert "UPDATE_KOTLIN_VERSION: 1.7.21"

---

gradle.properties

This reverts commit 572497a0fce0853fd3929e25985a49f72e45611d.

Revert "Revert "UPDATE_KOTLIN_VERSION: 1.7.21""

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

and minimize customizations in subclasses.

Configure KSP tasks with modern KGP APIs

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/DualLookupTracker.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSClassDeclarationDescriptorImpl.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspConfigurations.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/resources/kmp/annotations/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-js/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/playground-mpp/workload/build.gradle.kts

by `git revert 1.7.21-1.0.8..1.8.0-Beta-1.0.8`. Ugly but safer than local builds.

Revert to 1.7.21 and bump to 1.7.22

---

compiler-plugin/build.gradle.kts
gradle.properties
settings.gradle.kts

and clean up composing build with Kotlin.

UPDATE_KOTLIN_VERSION: 1.8.20-dev-3737

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt

that would disable execution optimization. See below for details: https://docs.gradle.org/7.2/userguide/validation_problems.html#implementation_unknown

Do not pass lambda to task actions

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeParameterImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeParameterEqualsProcessor.kt
test-utils/testData/api/libOrigins.kt
test-utils/testData/api/typeParameterEquals.kt

Use correct psi implementation for finding type parameter declaration.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeParameterReferenceProcessor.kt
test-utils/testData/api/typeParameterReference.kt

fix type resolution for java type parameters.
fixes #1250

fix psi look up for java type parameter descriptors.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Tested with build scan manually; no easy way to automate the test.

Defer realization of compilation tasks

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt

Support kotlin.native.useEmbeddableCompilerJar=false

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt

Exclude generated libraries from deps

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/SourceSetConfigurationsTest.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt
integration-tests/src/test/resources/kmp/annotations/build.gradle.kts
integration-tests/src/test/resources/kmp/workload-js/build.gradle.kts
integration-tests/src/test/resources/kmp/workload/build.gradle.kts
integration-tests/src/test/resources/playground-mpp/workload/build.gradle.kts
test-utils/testData/api/functionTypeAnnotation.kt
test-utils/testData/api/nullableTypes.kt

1. Updating the construction call to BasicMap with IncrementalCompilationContext.
2. Dropping js(LEGACY) tests.

UPDATE_KOTLIN_VERSION: 1.9.0-dev-877

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/playground/gradle.properties

set language version to allow KSP with FIR compiler

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/AndroidIncrementalIT.kt

(cherry picked from commit 67b1a5ffc6ed335e6cec5582952a56cea733fa61)
fix 1.0.10-release branch merge conflict.

remove module name mangling workaround

---

examples/multiplatform/test-processor/src/main/kotlin/TestProcessor.kt
examples/playground/test-processor/src/main/kotlin/TestProcessor.kt

fixes #1285, where incremental compilation is broken by incorrect incremental processing.

Fix incremental settings in examples

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/PlatformInfo.kt
common-util/src/main/kotlin/com/google/devtools/ksp/KspOptions.kt
common-util/src/main/kotlin/com/google/devtools/ksp/processing/impl/PlatformInfoImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPCompilerPluginTest.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KSPCommandLineProcessor.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt

Fixes https://github.com/google/ksp/issues/627

Add jvm-default mode value in JvmPlatformInfo

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
test-utils/testData/api/annotationWithDefaultValues.kt

fix annotation default class reference value for annotation declared in java source.

---

build.gradle.kts
common-util/build.gradle.kts
compiler-plugin/build.gradle.kts
gradle.properties
kotlin-analysis-api/build.gradle.kts
settings.gradle.kts
test-utils/build.gradle.kts

by adding dependencies explicitly.

Get rid of intellij Gradle plugin

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyAccessor.kt
common-util/src/main/kotlin/com/google/devtools/ksp/visitor/CollectAnnotatedSymbolsVisitor.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyGetterDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertySetterDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyAccessorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSPropertyGetterSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSPropertySetterSyntheticImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/LocalDeclarationProcessor.kt
test-utils/testData/api/declarationsInAccessor.kt

support local declarations for property accessors

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
test-utils/testData/api/annotationWithDefaultValues.kt

fix annotation default value evaluation for array initializers

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/NestedAnnotationProcessor.kt
test-utils/testData/api/nestedAnnotations.kt

fix nested annotation type resolution with usesite target

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/PackageAnnotationProcessor.kt
test-utils/testData/api/packageAnnotations.kt

KSP side effort for fixing #1378 , further fix is still needed in `XProcessing`

Support package level annotations.

---

common-util/src/main/kotlin/com/google/devtools/ksp/processing/impl/KSTypeReferenceSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSAnnotationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSClassDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSValueParameterImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/NestedAnnotationProcessor.kt
test-utils/testData/api/nestedAnnotations.kt

https://github.com/google/ksp/commit/610f42d307753c8b5bbeecd7b5f9fe80eef16048 is needed for compiling after import statement changes in https://github.com/google/ksp/commit/a4258bd8a5c4731e91b6c2b06669dabc7bf4016e . ideally 610f42d should be cherry-picked before but due to commit involving aa code it was skipped.

fix 1.0.12 release branch

---

.github/workflows/auto-merge.yml
gradle.properties
kotlin-analysis-api/build.gradle.kts

Also replaced `kotlin-compiler` with `kotlin-compiler-for-ide`.

Split dependencies and allow auto-merge for AA

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KtAlwaysAccessibleLifeTimeTokenProvider.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt

Update AA version to 1.9.20-dev-6963

---

gradle.properties

UPDATE_KOTLIN_VERSION: 1.9.20-dev-6963

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSValueArgumentLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt

also supported annotation default argument evaluation from Java source & limited support for libraries

AA: support java annotation argument evaluation

---

gradle.properties
kotlin-analysis-api/build.gradle.kts

which are provided by kotlin-compiler but not kotlin-compiler-for-ide.

AA: Add missing dependencies

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

Note that there is a separate commit for AA so that it can be auto-picked.

UPDATE_KOTLIN_VERSION: 1.9.30-dev-1098

---

gradle.properties
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

so that to unblock auto-merge.

UPDATE AA version: 1.9.20-dev-9102 for 1.0.14-release

---

api/api.base
api/build.gradle.kts
api/src/main/kotlin/com/google/devtools/ksp/utils.kt
build.gradle.kts
buildSrc/src/main/kotlin/com/google/devtools/ksp/ApiCheck.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/TemporaryTestProject.kt
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/impl/test/KSPAATest.kt
kotlin-analysis-api/testData/visibilities.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ExitCodeProcessor.kt
test-utils/testData/api/exitCode.kt
test-utils/testData/api/visibilities.kt

most commits are cherry-picks from main. Only manual commit here is the last one where kotlin version is updated and JDK target test is also updated (to unblock integration test, the test results are off due to commits not cherry picked into release branch).

update Kotlin 1.9.10 for 1.0.14 release branch

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt

This is a workaround for https://github.com/google/ksp/issues/1522

Manually compare by name when checking if a task should be enabled

---

integration-tests/build.gradle.kts

so that it can run individually.

Fix dependency of integration-tests

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KSPConfig.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt

Implemented the above features

KSP 2: excludeProcessor, JvmPlatformInfo, build cache

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

instead of KotlinCompilation. Same as KSP 1.0.
This is a workaround to a dependency resolution issue specific to Android variants.

KSP 2: Get libraries from compile task

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSDefNonNullReferenceImpl.kt
kotlin-analysis-api/testData/parent.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ParentProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

New behavior changes a lot in terms of synthetic members and ordering,
it is infeasible to adjust test processor logic to get tests aligned.

fork test for parent node.

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

KotlinCompilation.source() is deprecated.
Fixes #1529

Add generated source set with new KGP API

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/testData/annotationValue/java.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

also fork test with inconsistent enum entry types per the behavior change in FIR.

clear TODOs in enum entry implementation

---

DEVELOPMENT.md
README.md
api/src/main/kotlin/com/google/devtools/ksp/processing/ExitCode.kt
common-deps/build.gradle.kts
common-deps/src/main/kotlin/com/google/devtools/ksp/KSPConfig.kt
common-deps/src/main/kotlin/com/google/devtools/ksp/KspGradleLogger.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspGradleLogger.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
integration-tests/build.gradle.kts
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalMultiChainIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/incremental-multi-chain/processors/src/main/kotlin/Aggregator.kt
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KSPConfig.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KSPLoader.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KspGradleLogger.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSDefNonNullReferenceImpl.kt
kotlin-analysis-api/testData/parent.kt
settings.gradle.kts
test-utils/build.gradle.kts
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ParentProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

mostly cherrypick with last commit ignoring 2 tests for `useK2` flag.

Fix 1.0.14-release branch build

---

.github/workflows/auto-merge.yml
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/GradleCompilationTest.kt
gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt

Merge changes from 1.0.14-release to main

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/HmppIT.kt

and cherry-pick #1575 into 1.0.13-release

UPDATE_KOTLIN_VERSION: 1.9.20-RC2

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/PlatformInfo.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSAnnotated.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSDeclaration.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSDeclarationContainer.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSModifierListOwner.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSNode.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyAccessor.kt
api/src/main/kotlin/com/google/devtools/ksp/symbol/KSReferenceElement.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSDeclarationDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSNodeDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSPropertyAccessorDescriptorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSDeclarationJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/java/KSNodeJavaImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSDeclarationImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSNodeKtImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyAccessorImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSConstructorSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/synthetic/KSPropertyAccessorSyntheticImpl.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/utils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt

which broke the CI. I'll re-land it after 1.0.14.

Revert: Make hierarchy in KSP API sealed

---

build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/Incremental.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/binary/KSDeclarationDescriptorImpl.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KSPCmdLineOptionsIT.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Note that d44ad7d9824aa0f073ce3c53e79361ae0f030d3b will be required to update to 2.0.0-Beta2.

1.0.15-release: update to Kotlin 2.0.0-Beta1

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

Implement package annotations

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle.properties

(cherry picked from commit a7dc926c48e2e11108a34169f7d4bd08ebac617c)

UPDATE_KOTLIN_VERSION: 1.9.22

---

build.gradle.kts

This commit escaped cherry-pick process in #1686

fix Java compatibility level for release branch

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt

Currently, all annotation types are implemented by KSTypeReferenceResolvedImpl so the short-name-check optimization doesn't help. The special treatment of type aliases is only required by the short-name-check optimization and therefore isn't needed as well.

Cache symbols for getSymbolsWithAnnotation

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/DeclarationOrderProcessor.kt
test-utils/testData/api/declarationOrder.kt

handle no jvm class file use case for declarationOrdering

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/DeclarationPackageNameProcessor.kt
test-utils/testData/api/declarationPackageName.kt

fix package name logic for non source symbols

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/getPackage.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/GetPackageProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

exclude root package from getPackage search scope

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/replaceWithErrorTypeArgs.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ReplaceWithErrorTypeArgsProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/testData/api/replaceWithErrorTypeArgs.kt

support default type for asType

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
kotlin-analysis-api/build.gradle.kts
symbol-processing-aa-embeddable/build.gradle.kts

1. Do not `bundle kotlin-stdlib`
2. Do not `bundle symbol-processing-api`
3. Make sure all bundled deps are properly renamed

Adjust bundled deps in KSP2

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
kotlin-analysis-api/build.gradle.kts
symbol-processing-aa-embeddable/build.gradle.kts

from prepare/compiler/build.gradle.kts of the latest kotlin repo.

Add missing dependencies

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ClassWithCompanionProcessor.kt
test-utils/testData/api/companion.kt

improve companion object checking logic

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeParameterImpl.kt
kotlin-analysis-api/testData/typeParameterVariance.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeParameterVarianceProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt

fix variance calculation for type parameter

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

downcast to FIR internal to get file class names

fix backing field checking for top level callables, 

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/DefaultFunctionProcessor.kt
test-utils/testData/api/interfaceWithDefault.kt

use proper scope for getting declared static memberscope

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
gradle.properties

(cherry picked from commit 82da631998fd1bbe98d73347ad1d07bf8962232d)

UPDATE_KOTLIN_VERSION: 2.0.0-Beta5

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
.github/workflows/nightly.yml

1.0.21-release branch was branched directly from main.

set release branch to 1.0.21-release

---

api/api.base
api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt
integration-tests/src/test/resources/playground/test-processor/src/main/kotlin/TestProcessor.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt

Resolves #1621
Supersedes #1649

Implement Resolver.getModuleName API

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

fix annotation default value parsing for arrays and class literals.

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/FunctionTypeProcessor.kt
test-utils/testData/api/functionTypes.kt

fix package name for library based symbols

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeParameterImpl.kt
kotlin-analysis-api/testData/typeParameterVariance.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/TypeParameterVarianceProcessor.kt

fix type parameter bounds

---

api/src/main/kotlin/com/google/devtools/ksp/utils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/testData/annotationValue/java.kt
kotlin-analysis-api/testData/annotationValue/kotlin.kt
kotlin-analysis-api/testData/parent.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

Return KSClassDeclarationEnumEntryImpl for enum entry annotation values.

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt

use safe cast for annotation type to declaration resolution

---

gradle.properties
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

* downgrade kotlin version to 2.0.0
* disable KSPAATest

1.0.22-release branch cleanup work.

---

gradle.properties
kotlin-analysis-api/testData/recordJavaAnnotationTypes.kt
kotlin-analysis-api/testData/recordJavaAsMemberOf.kt
kotlin-analysis-api/testData/recordJavaGetAllMembers.kt
kotlin-analysis-api/testData/recordJavaOverrides.kt
kotlin-analysis-api/testData/recordJavaResolutions.kt
kotlin-analysis-api/testData/recordJavaSupertypes.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaAsMemberOfProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaGetAllMembersProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaOverridesProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaProcessor.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/RecordJavaSupertypesProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPCompilerPluginTest.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
test-utils/testData/api/recordJavaAnnotationTypes.kt
test-utils/testData/api/recordJavaAsMemberOf.kt
test-utils/testData/api/recordJavaGetAllMembers.kt
test-utils/testData/api/recordJavaOverrides.kt
test-utils/testData/api/recordJavaResolutions.kt
test-utils/testData/api/recordJavaSupertypes.kt

Do not add Java sources, because an upstream change in the test module
adds them automatically.

UPDATE_KOTLIN_VERSION: 2.0.20-dev-3728

---

integration-tests/src/test/kotlin/com/google/devtools/ksp/test/KMPImplementedIT.kt

(cherry picked from commit 6bba35bbc97b5f3df058c3d6d9ce8cb24f689b6f)

Do not run testWasm on release branch

---

build.gradle.kts
common-deps/build.gradle.kts
gradle.properties
kotlin-analysis-api/build.gradle.kts
settings.gradle.kts
symbol-processing-aa-embeddable/build.gradle.kts

Also moved versions of build/runtime dependencies into gradle.properties

Fix stdlib versions in KSP2 pom files

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/annotationValue/java.kt
kotlin-analysis-api/testData/annotationValue/kotlin.kt

optimize annotation default value evaluation.

---

docs/ksp2.md

- fix typo
- fix capitalization of the word *GitHub*

Editorial improvements in ksp2.md

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyAccessorImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/LateinitPropertiesProcessor.kt
test-utils/testData/api/lateinitProperties.kt

fix property accessor modifier logic

---

docs/ksp2entrypoints.md

* Add Kotlin highlighting
* Fix unclosed string
* Add comment to "..." to prevent highlighting issues
* Fix `processorProviders` variable usage

Improve docs/ksp2entrypoints.md

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml

1. Enable manual trigger
2. auto-merge: rebase again before push, so that multiple auto-merge can run in parallel.

Fine tune CI

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/replaceWithErrorTypeArgs.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ReplaceWithErrorTypeArgsProcessor.kt

preserve nullability when replacing args

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSClassDeclarationEnumEntryImpl.kt
kotlin-analysis-api/testData/getSymbolsFromAnnotation.kt

fix annotations on enum entry declarations

---

common-util/src/main/kotlin/com/google/devtools/ksp/common/ErrorTypeUtils.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/replaceWithErrorTypeArgs.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ReplaceWithErrorTypeArgsProcessor.kt

fix error type replace logic after error type hint change

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/ThrowListProcessor.kt
test-utils/testData/api/throwList.kt

include synthetic accessors for checked exception

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/jvmName.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/JvmNameProcessor.kt
test-utils/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt

check light accessors for data class jvm name

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/signatureMapper.kt
test-utils/testData/api/signatureMapper.kt

special handling of inline value class signature

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AsMemberOfProcessor.kt
test-utils/testData/api/asMemberOf.kt

recursively substitute functions for compute asMemberOf

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSTypeReferenceImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeReferenceResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationOnReceiverProcessor.kt
test-utils/testData/api/annotationOnReceiver.kt

handle receiver annotation use site target

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaAsMemberOfProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaGetAllMembersProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaOverridesProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/processor/RecordJavaSupertypesProcessor.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPCompilerPluginTest.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/testData/recordJavaAnnotationTypes.kt
kotlin-analysis-api/testData/recordJavaAsMemberOf.kt
kotlin-analysis-api/testData/recordJavaGetAllMembers.kt
kotlin-analysis-api/testData/recordJavaOverrides.kt
kotlin-analysis-api/testData/recordJavaResolutions.kt
kotlin-analysis-api/testData/recordJavaSupertypes.kt
test-utils/testData/api/recordJavaAnnotationTypes.kt
test-utils/testData/api/recordJavaAsMemberOf.kt
test-utils/testData/api/recordJavaGetAllMembers.kt
test-utils/testData/api/recordJavaOverrides.kt
test-utils/testData/api/recordJavaResolutions.kt
test-utils/testData/api/recordJavaSupertypes.kt

branch originally branched from current 1.0.23-release branch.

set 1.0.24 release branch kotlin version to 2.0

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSValueArgumentLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/AbstractKSDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/annotationsRepeatable.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationsRepeatableProcessor.kt
test-utils/testData/api/annotationsRepeatable.kt

they were presented as containers

Expand repeated annotations in libraries

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/common/IncrementalContextBase.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/IncrementalRemoval2IT.kt
integration-tests/src/test/resources/incremental-removal2/build.gradle.kts
integration-tests/src/test/resources/incremental-removal2/settings.gradle.kts
integration-tests/src/test/resources/incremental-removal2/validator/build.gradle.kts
integration-tests/src/test/resources/incremental-removal2/validator/src/main/kotlin/Validator.kt
integration-tests/src/test/resources/incremental-removal2/validator/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
integration-tests/src/test/resources/incremental-removal2/workload/build.gradle.kts
integration-tests/src/test/resources/incremental-removal2/workload/src/main/kotlin/p1/K1.kt
integration-tests/src/test/resources/incremental-removal2/workload/src/main/kotlin/p1/K2.kt
integration-tests/src/test/resources/incremental-removal2/workload/src/main/kotlin/p1/Main.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/common/IncrementalContextBase.kt

Invalidate aggregating outputs on removal of any file

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSPropertyDeclarationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueArgumentImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/testData/api/deferredJavaSymbols.kt

as well as fixing KSValueArgumentImpl.defer().

Implement KSPropertyDeclarationJavaImpl.defer

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSValueArgumentLiteImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSTypeArgumentResolvedImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/locations.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/LocationsProcessor.kt
test-utils/testData/api/locations.kt

The difference in test results in KSP1 and KSP2 come from synthetic constructors in KSP2.

KSP2: Implement missing location()

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/mangledNames.kt

Also fork mangledName.txt for a minor difference in enum constructor.
Fixes #1640

KSP2: get module name from metadata

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/standalone/KspSourceModuleBuilder.kt
kotlin-analysis-api/testData/getPackage.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/GetPackageProcessor.kt
test-utils/testData/api/getPackage.kt

KSP2: Include all subdirectories in content scope.

---

kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/checkOverride.kt

Forking the test because there are two issues in KSP1

KSP2: Enable testCheckOverride

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

Associate KSP with the inputs to JavaCompile

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_java2.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/AnnotationArgumentProcessor.kt
test-utils/testData/api/annotationValue_java.kt
test-utils/testData/api/annotationValue_java2.kt
test-utils/testData/api/deferredJavaSymbols.kt

Resolve PsiAnnotation before getting its name

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/java/KSAnnotationJavaImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/annotationValue/annotationValue_kt.kt
kotlin-analysis-api/testData/annotationValue/defaultKClassValue.kt
kotlin-analysis-api/testData/annotationWithDefault.kt
kotlin-analysis-api/testData/annotationWithDefaultValues.kt

Simplify parsing of default values in JVM binaries

---

gradle.properties

UPDATE_KOTLIN_VERSION: 2.0.21

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt

Handle empty array in annotation arguments.

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml

Also rewrote the main CI so that it triggers on all release branches.

CI: Update release branch to 1.0.27

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt

Fixes https://github.com/google/ksp/issues/2159

Dispose of open URLClassLoaders when compilation is complete

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

See also: https://github.com/google/ksp/issues/2159

KSP2: Close processorClassloader

---

gradle-plugin/build.gradle.kts
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle.properties
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
symbol-processing-aa-embeddable/build.gradle.kts

Renaming of kotlinx.coroutines interfers with kotlin-stdlib.

Unbundle kotlinx.coroutines

---

api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt

Kdoc only change. 
See https://github.com/google/ksp/issues/1075

Kdoc: more details about what classpath is searched by Resolver

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KotlinFactories.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt
gradle.properties

UPDATE_KOTLIN_VERSION: 2.1.0-RC

---

gradle-plugin/src/test/kotlin/com/google/devtools/ksp/gradle/ProcessorClasspathConfigurationsTest.kt

Similar to existing  testConfigurationsForSinglePlatformApp()
Need code coverage for Variant API migration (https://github.com/google/ksp/issues/2250)

Add test for KSP source set configurations for Android app

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt
gradle.properties

See https://youtrack.jetbrains.com/issue/KT-71197

Adapt to removal of old JVM backend

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

by using the shared KotlinCoreEnvironment.underApplicationLock.

fix application service registration

---

compiler-plugin/build.gradle.kts
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSAnnotationImpl.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle.properties
kotlin-analysis-api/build.gradle.kts
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPAATest.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
symbol-processing-aa-embeddable/build.gradle.kts

Revert "UPDATE_KOTLIN_VERSION: 2.2.0-dev-745"

---

.github/workflows/auto-merge.yml

which was switched to read-only recently.

Update github actions permissions for auto-merger

---

.github/workflows/auto-merge.yml
.github/workflows/main.yml
.github/workflows/release.yml

(cherry picked from commit 1957ba08adb2a6d28184da69faeff6872c47b918)

Update actions/cache to v4.

---

compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingExtension.kt
compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/AbstractKSPTest.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt
gradle.properties
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/PlaygroundIT.kt

Downgrade to Kotlin 2.1.20

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspExtension.kt
gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt

This has been deprecated and has been messaged to be unsupported since KSP 1.0.8

No-op blockOtherCompilerPlugins

---

compiler-plugin/src/test/kotlin/com/google/devtools/ksp/test/KSPCompilerPluginTest.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/FunctionKindProcessor.kt
test-utils/testData/api/functionKinds.kt

Return static function kind if modifier has static modifier

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/mangledNames.kt

Sanitize dashes to underscore for internals

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

Use moduleName from compilerOptions if it exists

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSAnnotationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/resolved/KSAnnotationResolvedImpl.kt
kotlin-analysis-api/src/test/kotlin/com/google/devtools/ksp/test/KSPAATest.kt
kotlin-analysis-api/testData/libOrigins.kt
test-utils/src/main/kotlin/com/google/devtools/ksp/processor/LibOriginsProcessor.kt

and rewrite the tests. Fixes #2412

Fix origin of KSAnnotation

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSFunctionDeclarationImpl.kt
kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/util.kt
kotlin-analysis-api/testData/getSymbolsFromAnnotation.kt

Support KaDestructuringDeclarationSymbol

---

gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspAATask.kt

Don't disable KSP2 native tasks if cross compilation is enabled

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt
kotlin-analysis-api/testData/jvmName.kt

Fix getJvmName for accessors starting with `is`

---

build.gradle.kts
gradle-plugin/build.gradle.kts
gradle-plugin/lint-baseline.xml
settings.gradle.kts

This adds Gradle specific checks from androidx.lint:lint-gradle
For now, baseline all the issues.

Enable running lint in ksp gradle-plugin project

---

gradle.properties

Inspired by https://github.com/google/ksp/pull/2450
Similar to https://cs.android.com/androidx/platform/frameworks/support/+/42e530c1ccb9f7e3c7dcbdad990950b221c99050:gradle.properties;dlc=ae91f90838a9ee3b89336ec86afd6df7da4bf3df

Switch to Lint with K2 UAST

---

build.gradle.kts
kotlin-analysis-api/build.gradle.kts
symbol-processing-aa-embeddable/build.gradle.kts
symbol-processing-cmdline/build.gradle.kts
symbol-processing/build.gradle.kts

Validated that there are no changes to jars by running ./gradlew publishToMavenLocal
and comparing output jars using diffuse

Upgrade to the latest stable Gradle shadow plugin

---

gradle-plugin/build.gradle.kts
gradle-plugin/lint-baseline.xml

Test: ./gradlew gradle-plugin:uLB

Upgrade to the latest lint-gradle checks

---

DEVELOPMENT.md

Hey! Very minor, but I was reading through the documentation and noticed a small grammatical error in `DEVELOPMENT.md` - this PR just updates that (`otherwised` -> `otherwise`)

Small grammatical update in DEVELOPMENT.md

---

common-deps/src/main/kotlin/com/google/devtools/ksp/KspGradleLogger.kt
integration-tests/src/test/kotlin/com/google/devtools/ksp/test/OnErrorIT.kt
integration-tests/src/test/resources/on-error/on-error-processor/src/main/kotlin/ErrorProcessor.kt
integration-tests/src/test/resources/on-error/on-error-processor/src/main/kotlin/NormalProcessor.kt

Update: location is printed in front of the message, just like KSP1.

KspGradleLogger: print location in error()

---

README.md
build.gradle.kts

OSSRH was deprecated on 2025.6.30.

Publishing: Switch to Central Portal

---

kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/KotlinSymbolProcessing.kt

Replace KaFirStopWorldCacheCleaner with no-op implementation
This cache cleaner leads to flakey build failures in AndroidX. KSP has already updated to a Kotlin AA version which no longer registered the cache cleaner by default for standalone but it is still registered for all other usages. This CL replaces it with a no-op implementation.

Replace KaFirStopWorldCacheCleaner with no-op implementation
